### ISSUE TITLE
Updates when moving to the plugin infrastructure

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#1]
During the transfer to the hydromt plugin architecture several core updates were done that will impact the transfer of the different models. These are:

- remove DATADIR and DATA_LIBS from the global vars
- all models need to have their own _DATADIR attributes (needed for example in the read_config method of model_api)
- parse_data_sources default path argument changed from DATA_LIBS to None
- the _write_xy function was transferred from sphincs.py to io.py
- in data_adapter, from_global_sources now raises NotImplementedError (to be fixed)
- in model_api __init__ data_catalog.from_global_sources() is temporarily commented out
- version set manual in hydromt/__init__.py

**Comment by hboisgon** [comment]
When updating with the new basin_mask, the following need to be updated:

- parse_region is in worflows.basin_mask (region.py does not exist anymore)
- subbasin with preliminary bbox is now using bounds keyword instead of bbox
- new handling of mask inside of flw.flwdir_from_da
- get basin_geometry returns a geopandas.GeoDataFrame instaed of a xy tuple as a second argument

**Comment by DirkEilander** [comment]
hydro_merit has been renamed to merit_hydro starting from artifacts v0.0.2

**Comment by DirkEilander** [comment]
I think we can archive this issue one year after our successful move to a plugin infrastructure
