### ISSUE TITLE
reduce repos size by pruning history

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#103]
The repository has grown quite big (>130MB) mainly because of large png and ipynb files in the documentation. There are some tools and guidelines to remove files from the git repository, but all should be used with utmost care! This is also best to execute at a moment when developments are frozen as everyone working on the repository will have to rebase their work after we have committed the purged history. There are also some [options to not clone the full repos](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) to make it a bit faster (but some come with limitations). 

TODO:
- [x] _(short term)_ make sure that we do not longer commit large png files and remove executed ipynb from docs 
- [x] remove doc versions from before v0.4
- [x] prune all history of the gh-pages branch
- [ ] avoid pushing large files (fonts, others) to this branch

[git filter-repo](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html), see also this [git help](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#using-git-filter-repo)

**Comment by DirkEilander** [comment]
@visr Any experience with this or pointers to good references?

**Comment by visr** [comment]
I haven't used git filter-repo, but I did use BFG once with success. Usually it's only a few files that make up the bulk of the size.

For the docs, probably it's enough to only keep the latest patch release of each breaking release, e.g. 0.1,0.2,0.3,0.4?

**Comment by savente93** [comment]
I've cleaned up the documentation branch history which did indeed make a big difference. It's still a bigger repository than I'd expect, but for now this should be okay, so I'll close this issue. We can open up another one in the future if necessary
