### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#1074]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

The following links do not work anymore (is that intended?):

- https://deltares.github.io/hydromt/latest
- https://deltares.github.io/hydromt/stable

This one does: https://deltares.github.io/hydromt/ but the version dropdown does not show any versions so seems older versions of the docs cannot be accessed at the moment?

### Current behaviour

Non v1 docs are not available and stable/latest links are broken

### Desired behaviour

Docs should be accessible

**Comment by savente93** [comment]
Fixed this now, problem was a syntax error in the `switcher.json`
