### ISSUE TITLE
`Model.logger` not available

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/hydromt#1080]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

The code below raises `KeyError: 'logger'`
```python 
from hydromt.model import Model
mod = Model()
mod.logger
```

### Current behaviour

 `KeyError: 'logger'`

### Desired behaviour

I think I read here it should now be a new property of `Model`:
https://github.com/Deltares/hydromt/blob/main/docs/guides/plugin_dev/migrating_to_v1.rst#logging

**Comment by savente93** [comment]
Under the header **changes required** it states this:

> Remove the logger keywords from your HydroMT functions, methods and classes. If you want to influence HydroMT logging, change the "hydromt" logger: `logger = logging.getLogger("hydromt")`.

once you use the built in logging.getLogger function you should be able to use the logger as you'd be used to

**Comment by veenstrajelmer** [comment]
Sorry, indeed I misread. I have updated the hydromt_delft3dfm PR accordingly. I will close this issue now.
