### ISSUE TITLE
method for cf-compliant & gdal understood nc files

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#117]
Currently we need to combine a couple of (rioxarray and hydromt raster & gis_utils) methods to create cf-compliant nc files which could be wrapped in a single hydromt.raster method for convenience:

```
crs = self.staticmaps.raster.crs
if ds.raster.res[1] < 0: # write data with South -> North orientation
    ds = ds.raster.flipud()
x_dim, y_dim, x_attrs, y_attrs = hydromt.gis_utils.axes_attrs(crs)
ds = ds.rename({ds.raster.x_dim: x_dim, ds.raster.y_dim: y_dim})
ds[x_dim].attrs.update(x_attrs)
ds[y_dim].attrs.update(y_attrs)
ds = ds.drop_vars(["spatial_ref"], errors="ignore")
ds.rio.write_crs(crs, inplace=True)
ds.rio.write_transform(self.staticmaps.raster.transform, inplace=True)
ds.raster.set_spatial_dims()
```

see also https://github.com/Deltares/hydromt_wflow/blob/19f135e95900406a2915574b87e00ff9c83d2d98/hydromt_wflow/wflow.py#L1865

**Comment by hboisgon** [comment]
Implemented with method gdal_compliant in raster.py
