### ISSUE TITLE
Add additional rainfall datasets

### ISSUE THREAD

**Issue by markhegnauer** [Deltares/hydromt#119]
Discussed with Frederiek Sperna Weiland about the following dataset:
- SM2RAIN-ASCAT (2007-2019): global daily satellite rainfall from ASCAT soil moisture | Zenodo

Might be an interesting dataset to add to our data catalogue, e.g. for calibration of our hydrological model.

**Comment by DirkEilander** [comment]
@markhegnauer is this the same data: p:\wflow_global\forcing\SM2Rain_ASCAT\ ??

**Comment by IMarth** [comment]
Added rainfall data set to deltares_data.yml with merging PR #156.
