### ISSUE TITLE
type hinting for api

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#127]
For the dashboard we need to add type hints for all public methods of the Model class.
For all arguments requiring a data source name or path to dataset (by convention ending on _fn) we will define our own types. 
This will enable us to select the right datatypes in a dropdown in the dashboard.

Suggested type (in api.py):
```
from typing import Union
from pathlib import Path
RasterDatasetSource = Union[str, Path]
GeoDatasetSource = Union[str, Path]
GeoDataframeSource = Union[str, Path]
```

Applicaton in plugin (e.g. in hydromt_wflow/wflow.py)
```
WflowModel(Model):

  def setup_maps(self, map_fn: RasterDataSource):
      pass
```

**Comment by Tjalling-dejong** [comment]
Added type hinting for raster dataset sources and geodataset sources for all hydromt plugins. Deltares/hydromt_dash#20

**Comment by Tjalling-dejong** [comment]
all commits are on fn_typing branch for each hydromt plugin repo

**Comment by Tjalling-dejong** [comment]
Check if geodataframeSource typing is correct based get_geodataframe instead of GeoDataSetSource

**Comment by Tjalling-dejong** [comment]
Add suggested types in hydromt/data_adapter/typing.py , to be called by model plugins
