### ISSUE TITLE
support getting data from GEE

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#138]
GEE data is cataloged in STAC https://gee.stac.cloud/?t=catalogs 
A potential useful package could be https://github.com/aazuspan/wxee

**Comment by ArjenHaag** [comment]
If indeed feasible, it would be nice if this could land within https://github.com/Deltares/hydromt/blob/main/hydromt/io.py

**Comment by DirkEilander** [comment]
with many of the other issues around data / cloud etc going on I wonder if this is worth pursuing. I'm going to close this issue for now. We can always reopen if we decide this still has added value on top of all the other developements.
