### ISSUE TITLE
editable install instructions

### ISSUE THREAD

**Issue by visr** [Deltares/hydromt#14]
I see in the installation manual, for developers an editable install is suggested. However it seems this is not possible without a setup.py present:

```
(geo) PS D:\repo\hydrology\hydromt> pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: D:\repo\hydrology\hydromt
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

(geo) PS D:\repo\hydrology\hydromt> pip --version
pip 21.0.1 from C:\bin\miniforge\lib\site-packages\pip (python 3.8)
```

Would you consider adding a setup.py, or do you have another way I can do an editable install?

**Comment by visr** [comment]
Apparently according to these links it's possible to make this work with a simple setup.py stub:
https://setuptools.readthedocs.io/en/latest/setuptools.html#id4
https://stackoverflow.com/a/62983901

```python
import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

Though I see this project is using flit, and I just did `flit install -s` and it worked the same, without a setup.py:
https://flit.readthedocs.io/en/latest/cmdline.html#flit-install

**Comment by hboisgon** [comment]
Yes sorry for that, it's still in one of our issue to update the install instructions in #2

**Comment by DirkEilander** [comment]
this has been fixed, see https://deltares.github.io/hydromt/latest/installation.html#developper-install
