### ISSUE TITLE
setup_response_unit: Options

### ISSUE THREAD

**Issue by couasnonanais** [Deltares/hydromt#151]
For the response_unit, multiple options/properties may be needed:

- provide a shapefile with to define the hydrological response units. 
- Compute the units from global data using the basin or subbasin keywords. Needs a DEM and extra splitting properties such as upstream area or a PFAF id threshold or a user defined (for example for property-based: elevation classes and land uses). If DEM-based, should return the "routing" too

- To include: 
-- argument to split further or not (from bbox and geoms for example)

_Example .ini:_
[setup_response_unit]
region (obtained via cmd: 'geom', 'bbox', etc.)
split_regions = False by default
split_method = "us_area", "pfaf_level" (--> could also be by passing the arguments directly but maybe for documentation maybe better?) --> OR could be removed and careful logging to explain to the user
provide keywords arguments needed for each method:
us_area_fn, pfaf_level_fn,
dem_fn (not mandatory if you don't want to split the shapefile further)
required_variable for the direction/routing between the basins. Needs to check and rename to a standard name

[setup_group_response_unit] - optional 
"other?" (property-based rules)
(groups are based on specific attributes such as land cover, soil types, etc. Each response_unit can be (for two groups X% in first group, (1-X)% in second group)

For the setup_response_unit:

- Have a look at the model_api.setup_region
- For basin/subbasin: have to look at wflow.setup_basemaps and hydromt/workflows/basemap.py to get the basin/subbasin from the DEM data
- For the upstream_area pfaf level: hydromt/flw.py (converts back to xarray object). Maybe only one and check in

**Comment by bartvanosnabrugge** [comment]
Some notes for the splitting:
https://deltares.github.io/pyflwdir/latest/basins.html#Minimal-area-based-subbasins

**Comment by DirkEilander** [comment]
closing this issue given the different sub issues referred to above.
