### ISSUE TITLE
Kwargs with None need to be passed using 'null' in yml files

### ISSUE THREAD

**Issue by JoostBuitink** [Deltares/hydromt#152]
Currently, when passing `None` to a kwargs, the yml parser does not convert this to a Python `None` object. Instead, `null` should be specified in the yml file.

One possible solution is to accept for `None` in the yml file, and replace those with `null` before parsing to the yml reader. This would also mean that `null` values should be replaced with None before writing to a yml file.

**Comment by hboisgon** [comment]
Not sure if we should change behavior for None or just write better doc about this ? Maybe good to change still as in our docstrings None is used everywhere

**Comment by DirkEilander** [comment]
Proposed solution: document that None is not accepted and if it is a valid value for an argument it should be the default value. in yml files where you explicitly want to show that you use the default None that line could be commented in that case. In addition we can catch this error to throw a better error.
