### ISSUE TITLE
use bump2version for versioning

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#173]
with [bump2version ](https://github.com/c4urself/bump2version) and git actions we can automate versioning without it extra runtime.

example: 
https://williamhayes.medium.com/versioning-using-bumpversion-4d13c914e9b8

**Comment by DirkEilander** [comment]
edit the release guide

**Comment by savente93** [comment]
bump2version hasn't seen a release since 2020 and the highest supported version that is listed is 3.8, so that one specifically is probably not a very good idea, but if there is a need for this, I'm very happy to look into alternatives

**Comment by DirkEilander** [comment]
Good point. We want something that is maintained. My idea behind this issue is to have unique version numbers for each state of the main branch, also in between releases. In practice quite a few users use the latest developments, making it hard to reproduce results. This could potentially also be fixed in github workflows? Alternatively, we could release more frequently.

**Comment by savente93** [comment]
We actually do, it's the commit hash! However I do think there is indeed much we could do we aliviate this problem, it's something I'd be happy to work on down the line. It's deifnitely something that could be fixed or at least improved with GHA. Let's brainstorm a bit on things we could do to improve this

**Comment by DirkEilander** [comment]
We have tried several options in #455 and decided to not go ahead with this for now. I will therefore close this issue.
