### ISSUE TITLE
align names of drivers between data adapters

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#180]
Excel is sometimes referred to as xls , xlsx (GeoDataFrame) or excel (DataFrame).
My suggestion is to keep the xls, xlsx for backwards compatibility but in the docs and docstrings use excel everywhere.

**Comment by DirkEilander** [comment]
the `vector` driver is also used for different functions in GeoDataFrameAdapter and GeoDatasetAdapter. 
It would be good to have a one to one relation between drivers and functions regardless of the Adapter.

**Comment by savente93** [comment]
Outdated now as the new drivers for this still have to be written, so closing this.
