### ISSUE TITLE
Create get_region function in cli.api.py

### ISSUE THREAD

**Issue by Tjalling-dejong** [Deltares/hydromt#207]
**Issue definition**
We want to offer users the ability to inspect the region geometry and region properties before they initialize a model. 

**How**
Reuse the parse region part of the setup_region function in model_api.py for returning the region geometry of a given region dict.  

**Pseudo-code** 
- Initialize DataCatalog object
- Parse region dict
- If basin, subbasin, interbasin, outlet in region dict: Get hydrography raster dataset 
- If bounds not in region: update region with basin_index_fn
-  Get basin geometry
- update region dict with outlets and basin geometry

**Comment by DirkEilander** [comment]
fixed in #207
