### ISSUE TITLE
New DataCatalog to access dataset from externally hosted sites

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#213]
We should test if and how using datasets in externally hosted sites like ERA5 can work with HydroMT.

Suggestion is to:

- Start testing with the ERA5 datasets to retrieved and process it with HydroMT: was used in Microsoft planetary project, check if still working
- Check speed compromises and how hydromt handles building model with a combination of local (p drive) / hosted data
- Prepare a first version of data catalog for externally hosted datasets

**Comment by DirkEilander** [comment]
ERA5 GCS https://github.com/google-research/arco-era5

**Comment by hboisgon** [comment]
Closed as duplicate of #296
