### ISSUE TITLE
test with new shapely v2 instead of pygeos

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#228]
With geopandas v0.12, the new shapely v2 is supported and pygeos can be removed.
I suggest to create different test environments, one with shapely v1.x and pygeos and one with geopandas>=v0.12 and shapely>-2

see [geopandas changelog](https://github.com/geopandas/geopandas/blob/main/CHANGELOG.md), [shapely migration docs](https://shapely.readthedocs.io/en/latest/migration.html) and [shapely changlog](https://shapely.readthedocs.io/en/latest/release/2.x.html#version-2-0-0-in-progress)

**Comment by hboisgon** [comment]
This now created an AttributeError in our tests, so moving to priority to see the consequences

**Comment by hboisgon** [comment]
I fixed the test by testing an error exception on a non-empty geodataframe.

There is a lot places in the code where we test on *if gdf.crs is not None*. These may be prone to error in case of empty or not properly defined GeoDataFrames.
