### ISSUE TITLE
Create validate methods for data catalog and configuration file

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#236]
Right now, if something is wrong in a data catalog yml file or configuration ini file, the error messages can be a bit cryptic (example typo diver instead of driver in yml...).
Would be nice to get some validate methods either in the CLI or before started build/update so that users know something is wrong in the yml or ini file and not within hydromt.

**Comment by xldeltares** [comment]
As discussed with @hboisgon , sometimes the arguments put by the user are insufficient. Then the data cannot be parsed correctly. It takes a bit of trail and error to eventually get it right - a challenging process for less-experienced python users. 

What would help, is that the user can get a glimpse of the data during the validation, for example, by printing the meta data of the data or by printing first lines (in case of csv). That requires first reading the data. 

In case of reading all is insufficient, maybe also good to validate only one data source at a time (thinking about snakemake dry run workflow and run one workflow element at a time functions)
