### ISSUE TITLE
Add option to delineate subbasins using either streamorder of Pfafstetter thresholds

### ISSUE THREAD

**Issue by markhegnauer** [Deltares/hydromt#242]
In regions with no / or limited number of gauges, it's sometimes still useful to derive subbasins for analysis and recognizability by users / clients. In Pyflwdir there are already options to do this (https://deltares.github.io/pyflwdir/latest/basins.html), but these functions are not yet available through HydroMT. 

I would suggest implementing this in a way that the user, through the inifile can set this up:

[setup_subbasin]
subbasin_method = gauges / pfafstetter / streamorder / minarea / ... (so either user specified location, or automatic generation)
subbasin_method_threshold = 5 (for the automatic methods)

Linked to: https://github.com/Deltares/hydromt_wflow/issues/118

**Comment by hboisgon** [comment]
Nice suggestion thanks @markhegnauer !
I suggest to add these methods to flw.py and then access them in the setup method in hydromt_wflow (similar to basin_map that is already available)

**Comment by DirkEilander** [comment]
This also links to #159
