### ISSUE TITLE
JOSS: HydroMT installation

### ISSUE THREAD

**Issue by JannisHoch** [Deltares/hydromt#244]
As part of the JOSS review, I had to install HydroMT. Glad to report it worked as outlined in the documentation!

Two minor that may need to be improved:

1. The ``jupyter`` dependency is not installed by default in the HydroMT environment while it's needed to check the example notebooks. It's not a big thing to install it, but I would find it more elegant if it could be installed automatically.
2. It would be good to include the test whether the installation was succesful in the Installation Guide, i.e. the ``hydromt --models`` command.

**Comment by hboisgon** [comment]
Hi Jannis, thanks for the feedback! 
Tor un the example we recommend a different installation with the right yml containing jupyter notebook. But I see we did not include that file in the examples installation guide.
We prefer to leave the conda-install minimal to just the libraries you need to run hydromt.

Second point is also a good suggestion thanks!
