### ISSUE TITLE
replace hydromt ini file by toml or yml

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#252]
Because ini is not a fixed format and the values are not automatically interpreted/parsed to python base objects it would make sense to use toml instead which is now a default python library. We will first need to investigate how compatible the current ini file is with toml and then decide how to make the transition.

**Comment by DirkEilander** [comment]
This relates to #246

**Comment by roeldegoede** [comment]
### Description
Example of how to provide SFINCS input in .ini-file format and .yml-file format. Especially when user wants to provide multiple datasets_dep for the setup_dep method, .yml-file has a clear advantage in readability.
NOTE: that the bullets before dep_fn in yml-format are just dashes "-"

### .ini-file example:
[setup_config]
tref = 20100201 000000
tstart = 20100201 000000
tstop = 20100210 000000
alpha = 0.5
zsini = 0.5

[setup_grid]
x0 = 268650
y0 = 5018550
dx = 150.0
dy = 150.0
nmax = 272
mmax = 425
rotation = 0
crs = 32633

[setup_dep]
datasets_dep = [{"dep_fn":"merit_hydro", "zmax":10, "zmin":-5}, {"dep_fn": "gebco", "offset":1, "zmax":0,}]

### .yml-file example:
setup_config:
  tref: 20100201 000000
  tstart: 20100201 000000
  tstop: 20100210 000000
  alpha: 0.5
  zsini: 0.5

setup_grid:
  x0: 268650
  y0: 5018550
  dx: 150.0
  dy: 150.0
  nmax: 272
  mmax: 425
  rotation: 0
  crs: 32633

setup_dep:
  datasets_dep:
  - dep_fn: "merit_hydro"
    zmax: 10
    zmin: -5
  - dep_fn: "gebco"
    offset: 1
    zmax: 0

**Comment by Tjalling-dejong** [comment]
### .toml-file example:

```
[setup_dep]
[[setup_dep.datasets_dep]]
dep_fn = "merit_hydro"
zmax = 10
zmin = -5

[[setup_dep.datasets_dep]]
dep_fn = "gebco"
offset = 1
zmax = 0
```

**Comment by Tjalling-dejong** [comment]
I made an example notebook where I tested the conversion of ini files to toml configuration files. I discovered that toml does not support None values.  A solution would be to change None to an empty inline table or change it to false depending on the type of argument.

**Comment by roeldegoede** [comment]
If I understand you correctly, you cannot put "None" anywhere in the toml file, right? I don't think that is a problem. For this specific usecase, all default values in the python scripts are None for example, and you only provide a value  in the toml if needed (so you wil never prescribe a None value in the toml file)

**Comment by DirkEilander** [comment]
@Tjalling-dejong Could you share your scripts and example ini files? I think you can attach these to this issue.
You can also start a PR for this using toml for now (I think this should easily be replaceable if we decide otherwise). The PR should be able to accommodate both ini and toml (for now).

TODO
- [ ] add toml parser to config.py. Note that we will need a short postprocessing for absolute paths (see also configread method)
- [ ] in cli/main.py we should decide whether to use the toml parser or configread method. Also throw a PendingDeprecation warning if ini is used.
- [ ] update the documentation and examples.



> If I understand you correctly, you cannot put "None" anywhere in the toml file, right? I don't think that is a problem. For this specific usecase, all default values in the python scripts are None for example, and you only provide a value in the toml if needed (so you wil never prescribe a None value in the toml file)

I agree with @roeldegoede that the None should not have to be a problem as we should avoid having to set this in config.  Where does this occur?

**Comment by Tjalling-dejong** [comment]
The notebook and example ini/toml files are in the examples/config_file_tests folder. 

@DirkEilander I used the example wflow_build.ini for testing:

`
[setup_precip_forcing]
precip_fn       = era5_daily_zarr          # source for precipitation.
precip_clim_fn  = None          # source for high resolution climatology to correct precipitation.
`
"precip_clim_fn" is set to None. If you parse this to a dict and then to toml,  "precip_clim_fn" will not be included in the toml file.

Would that cause any problems?

**Comment by DirkEilander** [comment]
> `[setup_precip_forcing] precip_fn = era5_daily_zarr # source for precipitation. precip_clim_fn = None # source for high resolution climatology to correct precipitation.` "precip_clim_fn" is set to None. If you parse this to a dict and then to toml, "precip_clim_fn" will not be included in the toml file.
> 
> Would that cause any problems?

This argument is None by default, see https://github.com/Deltares/hydromt_wflow/blob/main/hydromt_wflow/wflow.py#L1466
It is redundant in this config file and should be removed.

**Comment by roeldegoede** [comment]
> ### .toml-file example:
> ```
> [setup_dep]
> [[setup_dep.datasets_dep]]
> dep_fn = "merit_hydro"
> zmax = 10
> zmin = -5
> 
> [[setup_dep.datasets_dep]]
> dep_fn = "gebco"
> offset = 1
> zmax = 0
> ```

This is already much better than the ini-file, but for longer lists, (imagine 5+ datasets), the .yml-format seems much cleaner.

**Comment by alimeshgi** [comment]
The final decision is to replace HydroMT ini file by yml.

**Comment by DirkEilander** [comment]
@Tjalling-dejong can you update #292 including the examples? Thanks!

**Comment by savente93** [comment]
Can this issue be closed given that it is marked as done?
