### ISSUE TITLE
New hydromt release for publishing hydromt dashboard

### ISSUE THREAD

**Issue by Tjalling-dejong** [Deltares/hydromt#263]
@DirkEilander 
@hboisgon 

A new release of hydromt is needed for publishing the hydromt dashboard. The dashboard needs access to api_get_region in api.py in order for it to work. This function is available in the api_get_region branch and will be merged soon.

We should think of what other features we want to include in the new release.

**Comment by DirkEilander** [comment]
We have started a project to get an overview of what needs to be done for a next release here: https://github.com/orgs/Deltares/projects/20/views/1
