### ISSUE TITLE
CRS not parsed correctly in recent fiona release

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#285]
Fiona release pinned to avoid incorrect parsing of the crs attribute in a geojson file.
Check if this issue is known downstream and if/when the pin can be released.

https://github.com/Deltares/hydromt/blob/312dd970a00ee629a6a5d818178789e34d12ba30/envs/hydromt-test.yml#L15

**Comment by Tjalling-dejong** [comment]
I have gone through the issues on the Fiona github repository and I cannot find any issues relating to this bug. 
Could you show me how to replicate this bug?

**Comment by DirkEilander** [comment]
Without the pin on the fiona version the crs of the model region is not parsed correctly when reading the region.geojson resulting in the following error in the tests.

`AssertionError: {'geoms.region': AssertionError(), 'region': AssertionError()}`

This needs more investigation. I can't find a related issue on the fiona issue tracker. Let's see if it is fixed in the next release which is due in a couple of days. If not we should dive deeper into the issue.
