### ISSUE TITLE
Docs: subbasin always needs snapping option

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#297]
I think to build a model using 'subbasin' keyword, you always have to use as well a variable-threshold pair like uparea or strord. This is not explained in the docs: https://deltares.github.io/hydromt/latest/user_guide/model_region.html 

Issue was mentioned here: https://github.com/Deltares/hydromt_wflow/issues/153

**Comment by alimeshgi** [comment]
@laurenebouaziz you earlier indicated your interest to review this. Do you still have time for this?
