### ISSUE TITLE
DOC: table layout HydroMT data catalog unreadible

### ISSUE THREAD

**Issue by sibrenloos** [Deltares/hydromt#300]
Layout of data catalog on wiki (https://deltares.github.io/hydromt/latest/user_guide/data_existing_cat.html) is no longer readible:

![TableLayout_unreadible](https://user-images.githubusercontent.com/75011151/223392256-9d50c71f-4c3d-4f91-ba23-dfa9297fb51b.png)

**Comment by savente93** [comment]
This seems to no longer be the case (when you follow the link) should this issue be closed?

**Comment by savente93** [comment]
ah my bad, I didn't think about that (it does show correctly on firefox). please disregard my previous comment

**Comment by DirkEilander** [comment]
I think this could be solved by removing the path argument, or only showing the filename without the path (which isn't relevant info anyway). The table is created in docs/conf.py where this issue should be addressed.
