### ISSUE TITLE
ENH: update MeshModel.mesh property based on recent xugrid developements

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#326]
### Feature Type

- Adding new functionality to HydroMT
- Changing existing functionality in HydroMT

### Enhancement Description

Previously xugrid would only allow one grid to be defined in a UgridDataset object and in our first definiton of MeshModel.mesh we assumed one 2D grid definition.
xugrid can now support several grids to be defined in one UgridDataset object so we can update and enhance MeshModel.mesh to also support multi grids (1D/2D/3D).
A decision needs to be taken how to store 1D/2D/3D meshes in the MeshModel.mesh property. 

### Feature Description

**MeshModel.mesh**
We have more or less two options on how to define MeshModel.mesh:

- Option 1 (preferred): ``UgridDataset`` containing all grid definition and variables
- Option 2: ``Dictionnary`` of single grid UgridDataset

For the high-level attributes:
``MeshModel.region`` would be the UgridDatasetAccessor.total_bounds and ``MeshModel.crs`` UgridDatasetAccessor.crs
Problem is that this supposes that all grids in MeshModel.mesh are in the same CRS. We could do a check and else give an error. Not sure how frequent this would be so plugins could decide to re-write these properties if they need to support meshes with grids in different CRS? 

**Selecting a specific grid in MeshModel.mesh**
In order to add new data variable (eg DEM) to MeshModel.mesh, we need to be able to select a specific grid (1D/2D/3D) for data processing. The assumption is that it would be possible to have multiple 1D or 2D or 3D grids so shortcut properties like ``MeshModel.mesh1d`` / ``MeshModel.mesh2d`` and ``MeshModel.mesh3d`` cannot really be added in the core.

The core should then be really flexible on grid selection based on grid_name and maybe a shortcut to easily check if the grid is 1D/2D/3D. In case of option 1, grid name should be able to be derived from the grid topology (grid_name_edge eg mesh1d_edge...) and in case of option 2 this would be the dictionary key. Maybe define a new ``MeshModel.get_mesh``(grid_name) to easily select a specific grid and related data variables.

Conventions and shortcuts on grid_name could be defined in specific MeshModel plugins (eg for Delft3D conventional grid names could be mesh1d, network1d, mesh2d, mesh3d).

**Adding data variables to MeshModel.mesh via setup_ methods**
We can still define generic method to add and resample data (eg DEM) for MeshModel.mesh. The generic method will however require the user to provide a grid_name in order to select the correct grid for resampling.
The names of the method will be updated in case the grid is 1D / 2D or 3D as the GIS methods will differ.

Eg of new/updated setup methods:
``setup_mesh2d_from_raster``(raster_fn, grid_name, ...) would (needs refinement):

- read raster_fn regular gridded external data
- extract from MeshModel.mesh the 2D grid_name
- interpolate raster_fn to grid_name
- add the new data to MeshModel.mesh using MeshModel.set_mesh(interpolated data)

``setup_mesh1d_from_pointvector``(vector_fn, grid_name) would (needs refinement):

- read point vector data
- extract from MeshModel.mesh the 1D grid_name and convert to geopandas.GeoDataFrame
- intersects the points with the 1D grid and add the required data attributes from point to grid
- go back from the GeoDataFrame to 1D UgridDataset
- add the new data to MeshModel.mesh using MeshModel.set_mesh(point_data)

**Adding or updating a grid to MeshModel.mesh**
Compared to a classic GridModel.grid, MeshModel.mesh definition cannot be easily done in one ``setup_mesh`` method. New grids can be added (eg add a 1D grid, a 2D grid) or grid definition could even be updated (eg extend the current 1D grid with additional lines like rivers/pipes etc). 
We need methods to be able to deal with this.

Usually such method would be called ``setup_mesh1d``, ``setup_mesh2d``, ``setup_mesh3d`` and would have a grid_name argument.

- Prepare a 1D/2D/3D grid schematization based on the method 'region' argument
- Call a method to add/update the new grid with name grid_name. 

Classically the last step would be calling MeshModel.set_mesh but I feel we may need a different name as this step would be quite different than just adding data variables (``MeshModel.update_mesh`` instead of ``MeshModel.set_mesh``?):

- In case of adding (new) grid_name, we add the new grid definition and potentially update the links of that grid to other (eg updating link1d2d in Delft3D-FM). So far, updating the links between several grids seems to be plugin specific so can be left out of the core.
- In case of updating an existing grid_name, we then need to replace the grid_name definition in MeshModel.mesh. An additional step here compared to adding is that if data variables for grid_name were already present, then the data is not 'valid' anymore and may need to be re-interpolated to the updated grid. Not fully sure how and if we could support it? A possibility is that when calling update_mesh(UgridDataset, grid_name), if UgridDataset contains all data variables that were already present in MeshModel.mesh for grid_name then we allow overwritting the data variables and else we throw an error. This would leave interpolating the existing data variables to the plugin (eg is setup_rivers, setup_pipes in Delft3D-FM where attributes of the 1D network like roughness and material are also added at the same time as the 1D lines).

### Additional Context

@hboisgon will discuss the best implementation with stakeholders and afterwards refine the issue

**Comment by hboisgon** [comment]
@xldeltares I tried to recap our conversation in the issue text. Could you check and see if you agree and if I missed something?

**Comment by DirkEilander** [comment]
Thanks for updating the issue! It would be a nice next step to try to boil it down to (a couple of) methods which need to be added with for each some pseudo code or good description of its function, perhaps split in multiple issues.

I'm not sure I get the issue with "adding or updating a grid to MeshModel.mesh"

> In case of updating an existing grid_name, we then need to replace the grid_name definition in MeshModel.mesh. An additional step here compared to adding is that if data variables for grid_name were already present, then the data is not 'valid' anymore and may need to be re-interpolated to the updated grid. 

Isn't this about the order in which you build your model? If you first setup / refine your mesh and then start adding variables to the mesh, then you don't need to update previously set variables right? This is the same with a regular grid. If you decide to work on a different resolution you need to rebuild from scratch. Perhaps I misunderstood the issue though.

**Comment by xldeltares** [comment]
Hi @hboisgon I wonder if the following two function `setup_mesh2d_from_raster(raster_fn, grid_name, ...)` and `setup_mesh1d_from_pointvector(vector_fn, grid_name)` are for setting up the mesh topology (required and optional topology attributes, aka the grid) or mesh variables? From the name if looks like the former but the descriptions look a bit like the latter.  Would it make sense to separate into two separate functions?

This also related to the `MeshModel.update_mesh`. I think it is really handy especially when only mesh variables are added, but I wonder if that should be a complete different function, so each plugin can choose to either use it or not? e.g. In Delft3D FM, the model input file can either contain the topology attributes only, or _occasionally_ also contain mesh variables (such as bedlevel which can be written into the mesh input file or provided separately). In this case, I guess the steps to set up a 2D model in Delft3D FM would be:

- 1) (required function to setup mesh topology) `setup_mesh2d` --> setup_mesh2d
- 2) (optional function to setup mesh topology) `refine_mesh2d` --> get_mesh2d, refine mesh2d, set_mesh2d
- 3) (optional function to setup optional mesh topology attributes) `update_mesh2d_from_raster(raster_fn = dem)`  --> read raster_fn, get_mesh2d, interpolate dem to mesh2d (nodesor faces, depending on how the plugin prefers), add new data variable in mesh2d, set_mesh2d
- 4) (optional function to setup model data) `setup_maps_from_raste r(raster_fn = infiltration)` --> read raster_fn, add auxiliary data to the mesh2d extent
- 5) (optional function to setup model data) `setup_maps_from_raster_reclass (raster_fn = landuse)` -->read raster_fn, add auxiliary data to the mesh2d extent

When updating the 2D model, I imagine only the 2) 3) 4) 5) can be updated. If 1) changes, everything needs to be redo.

**Comment by hboisgon** [comment]
Hi @xldeltares. Thanks for commenting! Below my answers.
> Hi @hboisgon I wonder if the following two function `setup_mesh2d_from_raster(raster_fn, grid_name, ...)` and `setup_mesh1d_from_pointvector(vector_fn, grid_name)` are for setting up the mesh topology (required and optional topology attributes, aka the grid) or mesh variables? From the name if looks like the former but the descriptions look a bit like the latter. Would it make sense to separate into two separate functions?
This would be the latter. setup_mesh2d_from_raster follows the setup_maps_from_raster and setup_grid_from_raster, they are just here to add more data variables resampled to either mesh2d grid or raster grid. Methods that creates grid/mesh are called more setup_grid and setup_mesh and have a region kind of argument to be able to setup and define regular grid cells / mesh topology.

> 
> This also related to the `MeshModel.update_mesh`. I think it is really handy especially when only mesh variables are added, but I wonder if that should be a complete different function, so each plugin can choose to either use it or not? e.g. In Delft3D FM, the model input file can either contain the topology attributes only, or _occasionally_ also contain mesh variables (such as bedlevel which can be written into the mesh input file or provided separately). In this case, I guess the steps to set up a 2D model in Delft3D FM would be:
> 
> * 1. (required function to setup mesh topology) `setup_mesh2d` --> setup_mesh2d
> * 2. (optional function to setup mesh topology) `refine_mesh2d` --> get_mesh2d, refine mesh2d, set_mesh2d
> * 3. (optional function to setup optional mesh topology attributes) `update_mesh2d_from_raster(raster_fn = dem)`  --> read raster_fn, get_mesh2d, interpolate dem to mesh2d (nodesor faces, depending on how the plugin prefers), add new data variable in mesh2d, set_mesh2d
> * 4. (optional function to setup model data) `setup_maps_from_raste r(raster_fn = infiltration)` --> read raster_fn, add auxiliary data to the mesh2d extent
> * 5. (optional function to setup model data) `setup_maps_from_raster_reclass (raster_fn = landuse)` -->read raster_fn, add auxiliary data to the mesh2d extent
> 
> When updating the 2D model, I imagine only the 2) 3) 4) 5) can be updated. If 1) changes, everything needs to be redo.

Yes that would be the steps! Apart that for point 3) the function would be called setup_mesh2d_from_raster. For steps 4) 5), this makes me think we may want to add extra arguments to the setup_maps method to be able to select different bounds than self.region. Not sure if then we do that in your plugin or in core, if you can supply additional bounds or geom.

**Comment by DirkEilander** [comment]
> The real case I think is really for 1D mesh. Example we build 1D based on river shapes, then add pipes based on roads etc and in these databases potentially also some properties like manning, shape, diameter, width are part of the data you use to setup your 1D network. To make it easier, we splitted it into several methods (setup_rivers, setup_pipes) rather than one big setup_mesh1d also to be able to make assumptions and deal with river/pipe specific methods. We could decide tore-merge into one method setup_mesh1d(river_fn, pipes_fn, dem_fn etc) but the separate methods already had quite a lot of arguments...

I can see that use case and a single method is not a good alternative. You could in this case also save these 1D elements in the geoms attribute and only at writing (or when calling a `setup_1dmesh_from_geoms` method) convert to 1D mesh. Either way I think in the core it would suffice if the set_mesh methods 'just' adds a variable to the mesh similar to the other set_* methods.

**Comment by hboisgon** [comment]
For update mesh, just add a overwrite flag to be able to replace grid topology. False by default
