### ISSUE TITLE
create and publish a global pfafstetter based subbasin index for MERIT hydro

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#33]

**Comment by hboisgon** [comment]
Linked to Change Kaspian Sea status in HydroMerit
Currently Kaspian Sea is marked as lake in HydroMerit. This is not logical and makes using hydromt difficult. Ideally, Kaspian Sea is excluded from HydroMerit (like other ocean / sea).

**Comment by DirkEilander** [comment]
Chirstian worked on a Pfafstetter level 3 map for the global wflow model. See if we can reuse some of his work / scripts.

**Comment by DirkEilander** [comment]
I think this is outside the scope of HydroMT-core. But more like something for a SITO project. This issues around the Kaspian Sea will also be solved in #419
 
@hboisgon please reopen if you disagree.
