### ISSUE TITLE
ENH: OSM tiling (memory usage)

### ISSUE THREAD

**Issue by dalmijn** [Deltares/hydromt#345]
### Feature Type

- [X] Adding new functionality to HydroMT

- [ ] Changing existing functionality in HydroMT

- [ ] Removing existing functionality in HydroMT

### Enhancement Description

Tile a gridded dataset according to the OpenStreetMap structure.
Functionality exists within HydroMT, but has been quoted out due to memory issues.

### Feature Description

Use the '.raster' accessor to tile a gridded dataset as per OSM's system.

### Additional Context

Some information can be found [here](https://wiki.openstreetmap.org/wiki/Zoom_levels)

**Comment by DirkEilander** [comment]
@roeldegoede Could you elaborate a bit more on your use case for osm tiles? Do you need to be able to specify which zoom levels you want? and what the highest resolution zoom level should be or should this be based on the native data resolution? If we create a COG with with internal overviews and tiles aligned with the osm would that not be a better solution?
