### ISSUE TITLE
DOC: Pre-commit hook docs

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#358]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Location of the documentation

https://deltares.github.io/hydromt/latest/dev/contributing.html#code-format

### Documentation problem

Quite some typos in the text and link to pre-commit is not properly added.

Also it's not fully clear for me how to practically use it:
Install is clear

Usage: do I first have to do git add -  run pre-commit - git commit - git push
Or just run pre-commit without needing to do git add first?

Also would it be possible in the tests github actions to check if pre-commit was run? For example we have this for black to check if black was run and else throws error

### Suggested fix for documentation

Fix typos

**Comment by savente93** [comment]
I am working on adding some other things to pre-commit so I can take care of this at the same time
