### ISSUE TITLE
DOC: fix small mistakes in developper doc code format

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#371]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Location of the documentation

https://deltares.github.io/hydromt/latest/dev/contributing.html#code-format

### Documentation problem

Link to pre-commit and first code block

![image](https://github.com/Deltares/hydromt/assets/45457510/5e985f25-210b-4c70-b784-7ed6c26dd766)

### Suggested fix for documentation

Fix ink with _ at the end and fix code block indent

**Comment by savente93** [comment]
Thanks for reporting, I'll try to pick this up today or tomorrow.
