### ISSUE TITLE
Allow read/write options from the ini file

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#38]
Currently we cannot easily pass options to read/write methods outside of python.

A way to do this would be:
- pass options per function in the ini file
- in the build/update method collect these options and pass them when self.write is called.

Other implications:
-  Would be easier to have the general read/write method directley in the model api (no more abstract method)
- Model specific read / write (other than staticmaps, forcing staticgeoms)... are added to the model specific implementation of the read/write with flags when required.
- To avoid writing everything all the time some write_object could be added and turned on when set_object is called. Equivalent the flag is turned on for all object if a set_root is called after the model init.

**Comment by DirkEilander** [comment]
@hboisgon is this still relevant? In theory the read/write methods can take arguments if called from the ini file. Isn't that enough to accomplish this?

**Comment by DirkEilander** [comment]
@hboisgon I think we can close this after #76 Please reopen if you disagree.
