### ISSUE TITLE
Make HydroMT aware of model version

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#397]
### Kind of request

Adding new functionality

### Enhancement Description

t would be nice to make HydroMT aware of which model/software version it is working with. 

### Use case

For example, depending on software version, some additional input data might be needed and vice versa, or format of the readers/writers may be different. Tracking versions could also enable easily to update one model from a software version to another.

### Additional Context

Needs refinement but I guess we could add a model property for version and maybe work on dictionaries for which setup functions to use (and output to produce) and which readers/writers. Could also work within the functions with if/else statements but that would not make update of a model from one version to another easy.

**Comment by DirkEilander** [comment]
As a first step we can document which versions of the software are supported by a specific version of the HydroMT plugin. It would be good to do this in a consistent way (i.e. a new model attribute) which we can implement in the core and add to the logging.

**Comment by savente93** [comment]
As discussed today during sprint planning: simply adding a model version attribute to the model api is enough to close this issue. When the need arises for a more specific use case within the plug ins we can take it from there with a better understanding of the requirements.
