### ISSUE TITLE
Docker images for each of the supported python versions should be available

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#398]
### Kind of request

Adding new functionality

### Enhancement Description

Currently we only have one docker image which uses python 3.11 by default. For testing and deploying we should have docker images available for each of the different python versions we support.

### Use case

- Testing HydroMT with different versions of Python
- Speeding up the CI checks
- Deploying HydroMT in cloud environments (newest python versions aren't always supported in cloud environments)

**Comment by DirkEilander** [comment]
@savente93 Since you have fixed the tests & CI caching (first to use cases above) in a different way. And currently there is now hard pressing demand for docker images with other python version. Do you agree this issue can be closed?

**Comment by savente93** [comment]
Yeah that's okay with me, I guess I originally opened this as a matter of habit, but I agree that it's better to close this now, and open a new one if the need arises
