### ISSUE TITLE
Add latest landcover epoch map from VITO

### ISSUE THREAD

**Issue by rs9w33** [Deltares/hydromt#40]
Dataset in vito folder currently based on 2015 epoch. Yearly epochs up to 2019 are available (on Zenodo). 2019 epoch will be added to P drive (wflow_global\static_data\base\landcover\vito) and will need to be added to hydromt API.

Source: https://zenodo.org/record/3939050/files/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif?download=1

**Comment by markhegnauer** [comment]
I added now to the P-drive all epochs from 2015-2019. Next step is to update the read method for VITO to be able to import multiple "timesteps".

**Comment by DirkEilander** [comment]
done
