### ISSUE TITLE
Support Reading STAC catalog via HydroMT

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#404]
### Kind of request

Adding new functionality

### Enhancement Description

I want to be able to add a STAC catalog to my HydroMT catalog.
I do not want to manually copy metadata from a STAC catalog into the hydroMT catalog.

### Use case

I have data in a STAC catalog that I want to use in HydroMT.

### Additional Context

It would be great if open source STAC catalogs could be added to the predefined HydroMT catalogs

**Comment by DirkEilander** [comment]
As discussed this could come in two flavours. 
1. A (naive) `from_stac` method where we assume all required info can be found in the STAC entry. Potentially we could add HydroMT specific field in the STAC entry to make it less naive. 
2. We make it possible to point to a STAC entry from the HydroMT data catalog file to get the path and metadata information from STAC. Additional information required for HydroMT (e.g., driver_kwargs, unit conversion, renaming) can be added to the HydroMT data catalog file entry.
