### ISSUE TITLE
`to_stac` for creating STAC catalog from HydroMT catalog 

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#405]
### Kind of request

Adding new functionality

### Enhancement Description

I want to share my HydroMT catalog with STAC users. 

This can either be performed by making a HydroMT catalog readable with STAC APIS, however, this would complicate HydroMT users.
Instead, if I can create a STAC catalog using some HydroMT python function (and perhaps a CLI option?), I can easily create and update my STAC catalog using a HydroMT catalog.

About STAC spec: https://stacspec.org/en/about/stac-spec/

### Use case

I have a HydroMT catalog that should be readable via STAC.

**Comment by DirkEilander** [comment]
I don't remember discussing this option, but that would be interesting addition as well especially to use a STAC browsers to search the data. The first step to do this would be to identify the minimum required information for a STAC catalog entry and see if that is compatible with the HydroMT data catalog and/or whether we can get this from the data itself. Also, to my mind this functionality would fit better in a `to_stac` for the DataCatalog class. 

@Jaapel Is that also what you had in mind? If so, could you point us to a description of STAC which lists the minimal required fields. And if you see more use cases could you add these to the description.

**Comment by Jaapel** [comment]
Ok I thought we discussed both the STAC -> HydroMT catalog and HydroMT catalog -> STAC approaches. This one is about the latter. About the spec of STAC: https://stacspec.org/en/about/stac-spec/
There is also a stac-validator in python, maybe good for writing tests? https://github.com/stac-utils/stac-validator

**Comment by savente93** [comment]
So I've looked into this and the stac spec requies that you describe spatial and temporal bounds for stac items which I'm not sure we have for all stuff that's in hydromt. Perhaps this is a good thing to add into hydromt as well, but that will require more work. However, this could also go well together with the work of #356 Otherwise I'm not sure this is possible or at least feasable without that, so we might have to reject this after all. @hboisgon @DirkEilander what do you think?

**Comment by DirkEilander** [comment]
Those would indeed be nice attributes to add. However it would strictly speaking not be necessary if we are ok with inferring this information from the datasets when creating the stac items. I propose to add the attributes to the current data catalog specs and make a method that can infer these from the data.

**Comment by Jaapel** [comment]
Don't forget that STAC enabled extensions: https://github.com/radiantearth/stac-spec/tree/master/extensions#overview
This basically means that you can add your domain metadata (for for example hydrology) and have STAC services (e.g. catalogues and webservers) interact with your extension.

**Comment by savente93** [comment]
My other issues are blocked, so I'm picking this up next.
