### ISSUE TITLE
Geodataset from_gdf with different index len

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#415]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

It seems behavior of vector.GeoDataArray.from_gdf() changed in hydromt 0.7.0 linked to this PR: https://github.com/Deltares/hydromt/pull/276/files#

Before if you had `da = hydromt.vector.GeoDataArray.from_gdf(gdf, da_ts, index_dim="index")` the len of index in gdf and da_ts did not have to be equal (eg some station in gdf may not have data in da_ts but for the rest of the index there is no issue).
Since this PR the index in gdf and da_ts should be exactly the same name/len.

### Current behaviour

Return error if index in gdf is different than index in da_ts:

![image](https://github.com/Deltares/hydromt/assets/45457510/53ef3e25-6fa5-49a8-9ead-5737905a4bb6)

### Desired behaviour

I think it would still be nice if we don't match exactly on len the index in gdf and da_ts. We could even return NaNs if needed. This used to work before the PR mentioned above.

**Comment by hboisgon** [comment]
This was reported by [@Starphire1](https://github.com/Starphire1)

**Comment by B-Dalmijn** [comment]
This is resolved when a GeoDataFrame is passed into 'from_gdf' with an accompanying dataset of some sort with a different index (in length) compared to the GeoDataFrame and it still produces an outcome. This means that the method should not care about the fact that an index might be missing from the dataset. An exact match should be made. An easy fix could be filling up the index of the dataset and place NaN values for the variables of those indices.

**Comment by hboisgon** [comment]
This issue popped up again in CST project (more index on timeseries than on locs this time). So if it's okay I'll update the priority

**Comment by B-Dalmijn** [comment]
I'll get started on it soon then, @hboisgon
