### ISSUE TITLE
Support custom drivers to connect to data APIs

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#432]
### Kind of request

Adding new functionality

### Enhancement Description

We want to enable users to access data directly from custom APIs through the data catalog.  
This is especially relevant for observational data that gets updated frequently, but can be used in a broader context.

### Use case

There are two known use cases in plugins

- HydroMT-Wflow does uses the global water watch api: https://github.com/Deltares/hydromt_wflow/blob/74812afe1ad163258c1afe63bfecdb6a14e7900d/hydromt_wflow/workflows/waterbodies.py#L256
- HydroMT-FIAT uses an api for NSI data: https://github.com/Deltares/hydromt_fiat/blob/fiat_integrator/hydromt_fiat/workflows/exposure_vector.py#L125

### Additional Context

My initial thoughts:
-	Downloading data can be supported through custom “driver” functions which can be made available to the data adaptors via the entrypoints (similar to plugins). We need to provide a template for these functions. The data catalog file can be used to pass possible kwargs to these driver functions similar to the current drivers.
-	The actual functions should live in plugins and/or a separate package to avoid having to maintain these and related dependencies in HydroMT.
-	I think it would be good practice to cache the downloaded data in a subfolder of the model root with a yml file for reproducibility.

**Comment by DirkEilander** [comment]
@frederique-hub @roeldegoede @hboisgon Adding this issue based on our discussion yesterday. Let me know if this would work for you / if you have additional ideas.

@veenstrajelmer I understood that you may also have some thoughts on this?

**Comment by veenstrajelmer** [comment]
Indeed, we would like to connect to data from e.g. the CMEMS ocean model via an API and other datasets via OPeNDAP. Would be nice to be able to access them via hydromt directly. I would like to contribute to a discussion, or alternatively can provide you with a textual overview, or both. Let me know what you prefer.

**Comment by DirkEilander** [comment]
> Indeed, we would like to connect to data from e.g. the CMEMS ocean model via an API and other datasets via OPeNDAP. 

I think that OPeNDAP should already be possible as we use xarray.open_dataset for our netcdf driver. see https://docs.xarray.dev/en/stable/user-guide/io.html#opendap It would be good to verify this with a test.

**Comment by veenstrajelmer** [comment]
For an overview of functions that we would need to set up a simple model, you can have a look at the [functions in dfm_tools](https://github.com/Deltares/dfm_tools/blob/main/dfm_tools/download.py). Let's discuss this via teams or in person in the near future.

**Comment by jensdebruijn** [comment]
Would be awesome of ISIMIP API is also supported, including the cutout option: https://github.com/ISI-MIP/isimip-client/blob/master/notebooks/cutout.ipynb

**Comment by savente93** [comment]
Supporting individual APIs is too high a maintenance burden for core. I've looked at the suggested APIs and they all are built on protocols we already support (HTTPS we recently added support for in #499, and I quickly verified OpenDap is already supported through xarray). We're much better served putting the effort of supporting individual APIs into making sure that the adapters are flexible enough to support these API generically. 

I'll be closing this specific issue because all the mechanics to support these APIs are already there, and I'd encourage the people wanting to use these APIs through HydroMT to make data catalog entries for them (and if you do please submit a PR so we can add it to the main catalogs). However, if people find the drivers to have bugs, or lacking features such as the ability to pass specific parameters, I would encourage them to file bug reports or feature requests and I'll happily pick those up.

**Comment by DirkEilander** [comment]
This issue is mainly here to implement a system through which users could use the data catalog to connect to custom data APIs. We certainly should not aim to support many of these APIs in core for the reasons you mention apart from perhaps a few often used exceptions. Let's discuss further offline in the meeting I suggested earlier for next week.

**Comment by DirkEilander** [comment]
- the driver argument in  a catalog entry defines the custom driver
- we will provide a template for each Adapter with possible/required (tbd) arguments and required output object (e.g., pd.DataFrame for DataFrameAdapter)
- local vs global caching is defined in data catalogus 
- the core will not host any catalogus with custom drivers that are not defined in hydromt core
- the custom driver function is called in the _read_data method of the Adapter. 

TODO:
- [ ] how to import the custom driver (e.g., entrypoints or runtime import or ...)
- [ ] how to deal with arguments (decorator to match possible arguments with custom api arguments, or make all possible arguments required in the driver function)
- [ ] how to define the custom drivers per adapter (e.g., staticmethod, tests, etc)

**Comment by DirkEilander** [comment]
Thanks for looking into this @Jaapel! 

You are right that the arguments of the `get_data` method are different for each `DataAdapter` subclass. This is because not all data types have a spatial or temporal dimension and hence its get_data method no arguments to slice the data on those dimensions. 

I think that your approach is good. I think we would indeed need `RasterDatasetDriver`, `GeoDataFrameDriver`, etc classes, perhaps we can even generalize some methods in an `AbstractDriver` class like you suggest.  Users would than subclass the driver class for their type of data and implement a version of what is now the `XXDataAdapter._read_data` method (but than for a single driver), and optionally the `XXDataAdapter_resolve_path` method. Other methods of the `XXDataAdapter._read_data` are generic and do not need to be part of these Driver classes I think. A `write` method could be based on the `XXDataAdapter.to_file method`. Furthermore, I think these new `XXDriver` classes could also contain some of the functionality you proposed earlier in https://github.com/Deltares/hydromt/discussions/608

We can take inspiration from [xarray backends](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html) and its implementation with entrypoints in [xarray/backends/plugins.py](https://github.com/pydata/xarray/blob/main/xarray/backends/plugins.py). I.e., we would also need methods like `detect_parameters` to see which of the available get_data arguments are implemented and `get_backend` to work with entrypoints. 

Perhaps best to start with making a start for two data types, say `RasterDatasetDriver` and `GeoDataFrameDriver` and see what works best?

**Comment by DirkEilander** [comment]
Thinking a bit more about it. Couldn't the current `RasterDataAdapter`, `GeoDataFrameAdapter`, etc classes be the  `RasterDatasetDriver`, `GeoDataFrameDriver`, etc? We would than basically need to subclass the `RasterDataAdapter` for each driver we currently support (e.g., raster, zarr, netcdf, ..) and implement the `_read_data` method for that driver. To implement a custom driver one would do the same.

Either way it would be good to discuss what functionality should be in a possible new `Driver` class and what should be in the `Adapter` class. I also can image that the Driver class does the resolve_path, reading and slicing, the Adapter the other `get_data`  steps to ensure consistent naming, units, attributes etc.

**Comment by DirkEilander** [comment]
To help the design session I have attempted to make a small diagram of the current implementation and a start for the new design for discussion. The idea is similar to split the reading and preprocessing parts of the current `DataAdapter` class by introducing a new `DataDriver` class. This could be combined in a `DataSource` class which matches the terminology in the `DataCatalog` better and could be used to better e.g. close file handles etc.

When discussing the design it is important to keep in mind that we have static arguments that define are set in the DataCatalog files and define how to read the data (`driver_kwargs`) and how to preprocess the data (`rename`, `unit_mult`, `unit_add`, ..). These are easy to handle and should go to the `DataDriver` and `DataAdapter` classes respectively. However, we also have _at runtime arguments_ that depend on the application and depend on the data type (`bbox`, `time_tuple`, `zoom_level`, `variables`, etc,). These arguments should probably be passed to both classes, but not all drivers will/can use all. Not sure what the best way is to deal with this.

**v0.X**
![HydroMT_v0_Data_extended drawio](https://github.com/Deltares/hydromt/assets/15379728/7c15ef3b-b52c-4ac1-9760-2403e9533b7b)

**v1.0
![HydroMT_v1_Data_extended drawio](https://github.com/Deltares/hydromt/assets/15379728/d0ca9cbf-ff9b-4977-8733-a79d29175e1a)
 suggestion**
