### ISSUE TITLE
check dev dependencies in pyproject.toml

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#437]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

NA

### Current behaviour

Current dev dependencies
```
dev = [
    "black",       # linting
    "ruff",        # linting
    "pre-commit",  # linting
    "pip>=23.1.2", # needed for recursive dependencies
    "flint",       # needed to publish to pypi
    "wheel",       # needed to publish to pypi
    "twine",       # needed to publish to pypi
]
```

### Desired behaviour

I believe `flint` should be `flit` and `wheel` can be removed.

**Comment by savente93** [comment]
after some quick testing it seems you're correct. I'll open a PR for it
