### ISSUE TITLE
EHN: Support multiple timeseries files for creating a GeoDataset object

### ISSUE THREAD

**Issue by Tjalling-dejong** [Deltares/hydromt#453]
### Kind of request

Adding new functionality

### Enhancement Description

This issue was raised in #372. But the change is quite big, so a separate issue is the right thing to do.
 
The fn_data argument can be multiple (csv) files: for now geodataset require one file per variable with all IDs but for some data this could be organized as one file per ID (with all variables)

This issue depends on how issue #372 is solved. 

### Use case

@hboisgon Could you elaborate a bit more on the use case of this issue?

**Comment by hboisgon** [comment]
Sure! But I think you explained it yourself : `for now geodataset require one file per variable with all IDs but for some data this could be organized as one file per ID (with all variables)`

My current use case is for lakes/reservoirs where classically you have one file per lake ID with rating curve tables (ie A=f(H) and Q=f(H)). But it can also happens for meteo/water quality observation stations where they have sometimes an excel file with one tab per station (and pandas can only open one tab at a time).

**Comment by DirkEilander** [comment]
I think what we need to progress on this is a detailed description of how the csv/excel files look that we want to support. In your case each file (or tab) has data (can be multiple variables?) for a single location. But do we also want to support files with a single variables for multiple locations? How is the file linked to the geospatial index? Through file naming conventions of the csv file? Or a filename in the attribute table of the locations file? How do we set the names for dimensions and variables if we translate the files to a xarray.Dataset?

In the light of the discussion in #372 I would also argue against including this in the io.open_geodaset method. Instead my suggestion would be to make this a separate driver in the DataFrameAdapter (return a multiindex DataFrame) or a driver in a new DatasetAdapter.

**Comment by hboisgon** [comment]
Need to make a decision what we do want to support and see if this can be part of pre-processing or added in the data adapter
