### ISSUE TITLE
use of `entrypoints` should be deprecated

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#454]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

https://pypi.org/project/entrypoints/

### Current behaviour

Currently HydroMT uses the `entrypoints` packages to advertise entry points for the plugins to use. However the PyPi page of `entrypoints` lists the current paragraph: 

> This package is in maintenance-only mode. New code should use the [importlib.metadata module](https://docs.python.org/3/library/importlib.metadata.html) in the Python standard library to find and load entry points.  

### Desired behaviour

Whenever possible we should prefer dependencies that are actively maintained, therefore we should investigate the possibility of moving away from `entrypoints` and use the new standard library functionality for this if possible

**Comment by DirkEilander** [comment]
Thanks for spotting this! The alternative standard library seems like the go-to alternative. @savente93 could you research what is required to replace entrypoints by the standard library? We use it to define an entrypoint in the pyproject.toml files of plugins which points to an child of the Model class in that plugin. These entrypoints are found and loaded in hydromt/models/model_plugins.py
