### ISSUE TITLE
Documentation on the ini file

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#46]
In the core documentation, the ini file structure is missing, as well as good documenation on the behavior of the build update and clip method (bit mixed in the CLI). This includes:

- description of the ini file
- important components (setup_config always done first and setup_basemaps check)
- repeating of several components in the same ini is also possible with numbering (ex: setup_gauges, setup_gauges1, setup_gauges2).

**Comment by DirkEilander** [comment]
closed with #104
