### ISSUE TITLE
No link to the EVA notebook in the docs

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#464]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are wrong

### Location of the documentation

The EVA notebook was created with [PR 85](https://github.com/Deltares/hydromt/pull/85) but not added to the online docs.

Links should be added to make it findable in the docs in the pages:

- https://deltares.github.io/hydromt/latest/getting_started/examples_index.html
- https://deltares.github.io/hydromt/latest/user_guide/intro.html (methods and workflows menu)

Additionally maybe also mention something here: https://deltares.github.io/hydromt/latest/user_guide/methods_stats.html
(only the skills stats are mentioned)

### Documentation problem

See above

### Suggested fix for documentation

Include links

**Comment by savente93** [comment]
since this is such a small thing, it might be easy to just include it in #446 ? I'm updating that one to be in step with main now anyway, so I can add it there if you want

**Comment by hboisgon** [comment]
What you want but I still would like to add some texts / good practices for plugin developments in relation to HydroMT so not sure this one will be merged very soon. But you are right this is a very small thing so maybe like last time can be combined with other docs issues or another PR, I dont mind

**Comment by savente93** [comment]
I would say it depends on when you think you can work on the Plugin docs. If you plan on working on it in the next week or so, then we can leave it, other wise it might be better to put it in a separate PR anyway. I think it's becoming not to leave things like this for too long. Up to you.
