### ISSUE TITLE
EVA method not implemented to work with 2D dask array

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#469]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

I tried using eva method as shown in the examples/doing_extreme_value_analysis.ipynb with a larger datasets and found memory leaks.

The file I test with is 83MB and I can provide it if needed.

### Current behaviour

There are several leaks so far:
 
**get_peaks**

in L268, `first` method does not seem to work with dask array. As we want the time label rather than the discharge values, I suggest to use another method that is dask compatible (mean works) or use maybe a pandas method on the time values rather than on the full dataarray.

https://github.com/Deltares/hydromt/blob/50e50b5c67c09f644e2a1a3ee9521030068675fe/hydromt/stats/extremes.py#L264-L270

Error:

> NotImplementedError: 'first' with skipna=True is not yet implemented on dask arrays

**fit_extremes**

L409 calls a da_params.values which triggers a load and in my case MemoryError.

https://github.com/Deltares/hydromt/blob/50e50b5c67c09f644e2a1a3ee9521030068675fe/hydromt/stats/extremes.py#L408-L419

Error:

> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 27.5 MiB for an array with shape (4016, 31, 58) and data type float32

I see this is because if several distributions are used, it is not known which one will fit best. In case there is only one distribution, the following avoids the memory error:

```
    # split output
    if len(distributions) > 1:
        idist = da_params.isel(dparams=-1).values.astype(int)
        distributions = np.atleast_1d(np.array(distributions)[idist])
    else:
        # avoid memory error if only one distribution was used
        distributions = np.atleast_1d(np.full(da_params.isel(dparams=-1).shape, distributions[0]))
```

**get_lmom**

Last error I had (this one I did not solve) was on line 908 that `negative values are not allowed`. Not sure if it's because I use a 2D grid or something else. After that I switched to xclim.indices.stats.frequency_analysis instead of eva

https://github.com/Deltares/hydromt/blob/7a7883770099ce9b61595dd22e82d39308246eb5/hydromt/stats/extremes.py#L906-L909

### Desired behaviour

Avoiding memory issue as much as possible. Some suggestions are mentioned above.

**Comment by DirkEilander** [comment]
TODO: 
- fix get peaks in separate issue
- discuss if we need eva fit (or use e.g. xclim)
