### ISSUE TITLE
Rename LumpedModel.response_units to VectorModel.vector

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#474]
### Kind of request

Changing existing functionality

### Enhancement Description

Rename LumpedModel.response_units to VectorModel.vector
This is more consistent with GridModel and Meshmodel.

**Comment by hboisgon** [comment]
@DirkEilander is that the correct name?

**Comment by DirkEilander** [comment]
@alimeshgi I think this is a small issue which we want to do asap. Why did you move it to Q4?
