### ISSUE TITLE
XYZ (OSM): to png; webviewer

### ISSUE THREAD

**Issue by dalmijn** [Deltares/hydromt#488]
### Kind of request

Adding new functionality

### Enhancement Description

This is essentially an update of issue #345.
The feature request came about when I talked with @roeldegoede.
From this conversation, it became clear that the more prominent use case for tiling raster data would be the visual representation of the data, i.e. viewing the data in a webviewer.

This means that the `to_osm_tiles` method in the OSM branch is to be ported (whole new method) to a method that writes png files in the OSM structure. This will most likely be done with the `mercantile` package. This will then become an optional dependency. 

When the tiles are created and saved in a folder structure as follows `~/folder_to_png_files/{Z}/{X}/{Y}.png` 
QGIS's XYZ service should be able to handle it, which also means a webviewer can.

### Use case

Viewing data in a webviewer as images.

### Additional Context

Continue to work in the OSM branch.

**Comment by DirkEilander** [comment]
Fixed in #440
