### ISSUE TITLE
Connect to the DD STAC Catalogue

### ISSUE THREAD

**Issue by xldeltares** [Deltares/hydromt#50]
align DD STAC Catalogue with current data adapter and yml files as a new driver

**Comment by xldeltares** [comment]
Dirk:

I think intake-stac (https://github.com/intake/intake-stac)  is a good library to start exploring for this purpose and it’s probably useful to understand one of its key dependencies ffspec. This introductory video describes the intake-stac package well (https://www.youtube.com/watch?v=LfxhhOMmWqE). 
It would be nice if we could align it with our data adapter and yml files as a new driver.

**Comment by DirkEilander** [comment]
I think this is covered in #404 and I'm therefore going to close this issue.
@xldeltares please reopen if you disagree. Could you then also clarify what we need to do besides #404 to solve this issue.
