### ISSUE TITLE
BUG? Check if a data source is in DataCatalog

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#501]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

>>> import hydromt
>>> dc = hydromt.DataCatalog("artifact_data")
>>> "merit_hydro" in dc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'DataCatalog' is not iterable

### Current behaviour

This returns an Error that DataCatalog is not iterable while this use to work (return True or False) before and is used at least in hydromt_wflow plugin a couple of times...

Anyway maybe it was not the best way to check if a data source is in data catalog and the option *'merit_hydro' in dc.sources* is better and works but as it is used, I thought good to investigate why it does not work anymore and inform plugins accordingly before releasing.

### Desired behaviour

The Error could stay but the change in behavior should be reported.

**Comment by DirkEilander** [comment]
This has indeed been deprecated, but we can discuss if it is still required. The current syntax is 
```
"merit_hydro" in dc.get_source_names()
```
