### ISSUE TITLE
Improve diagrams in documentation

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/hydromt#529]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are missing

### Documentation problem

Improving diagrams in the documentation of the HydroMT involves enhancing the visual representations used to convey information, processes, and concepts related to the HydroMT software and its functionalities. Well-designed diagrams can greatly aid users, developers, and contributors in understanding and effectively utilizing the tool.

**Comment by savente93** [comment]
After having discussed this previously we decided that we should make multiple diagrams: Starting with diagrams only for users, to introduce what HydroTM does, then an overview of how runs work (the sequence) for advanced users and finally a overview of the archetecture and repository for developers
