### ISSUE TITLE
Building Docs is failing with xugrid import error

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#536]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

import xugrid raises on ImportError on xarray import_matplotlib_pyplot since the release of xugrid 2023.9.0
see: https://github.com/Deltares/xugrid/pull/163

### Current behaviour

While we wait for new release of xugrid we can put a temporary max on xarray version (xarray<2023.9) and once xugrid is released remove it

### Desired behaviour

/

**Comment by DirkEilander** [comment]
this is fixed with the new xugrid 0.6.5 release
I have removed the xarray pin in #531
