### ISSUE TITLE
Installation guide for examples is not up-to-date

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#546]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are wrong

### Location of the documentation

https://deltares.github.io/hydromt/latest/getting_started/examples_index.html

### Documentation problem

With make.py, the environment.yml file does not exist anymore so the recommended installation does not work anymore.

Related issue:
https://github.com/Deltares/hydromt_wflow/issues/206

### Suggested fix for documentation

Either update by explaining how to install and use make and add the tomli dependency.

Or do create maybe in the examples folder the correct environment.yml file (maybe can be automatically created in one of our github workflow?).
I still think that for most hydromt users who works with command line and are less handy with python, we should not complicate things too much, especially when it comes to installing and trying out the tool for the first time. So I would be in favor of the second option

**Comment by savente93** [comment]
Implementation pending decision, but I can pick this up when I work on #465. I have a small preference for the first, but don't really have strong feelings about it one way or the other.

**Comment by savente93** [comment]
@DirkEilander do you have strong feelings about this?
