### ISSUE TITLE
Supoprt for the `*_staticgeoms` functions should be removed in 1.0

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#553]
### Kind of request

Removing existing functionality

### Enhancement Description

This functionality is marked as deprecated and should therefore be removed in the next breaking change (or be no longer marked as deprecated)

**Comment by DirkEilander** [comment]
To be discussed: can we already remove this earlier? To my knowledge only wflow uses this and I suggest to remove it once they move the latest hydromt version. see https://github.com/Deltares/hydromt_wflow/issues/203

**Comment by savente93** [comment]
Fixed in #734
