### ISSUE TITLE
consistent IOErrors when writing model components in read-only mode

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#57]
There are some inconsistencies in the ModelAPI with regard to the read/write modes:
- missing IOError in write_config in read-only mode
- different warning messages when replacing maps
- IOErrors in set_ methods

My proposal is to only use IOErrors and check if read-only in the `write_` methods. The `set_` don't need a IOError as we are not writing anything and the error is also only thrown when the item already exists which is not consistent.

**Comment by hboisgon** [comment]
Closed with #58
