### ISSUE TITLE
HydroMT release v0.9.0

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#570]
### Kind of request

None

### Enhancement Description

We would like to release v0.9.0 in the week of Oct 16.
This issue is to identify which (last-minute) issues & PRs still need be finished before.

# minimal required:
- [x] PR #505 
- [x] PR #569

# nice to have
- [ ] PR #305 

@alimeshgi @savente93 @hboisgon @Jaapel @Tjalling-dejong: let me know in the comments below if this list is not complete

**Comment by savente93** [comment]
I think #546 is also required

**Comment by hboisgon** [comment]
I agree with the list and the extra suggestions from Sam:

- #546 is needed 
- #465 is nice-to-have especially if we decide to do some code to download the right examples version. At least for the release we could already document how to manually install the right examples version

**Comment by hboisgon** [comment]
Another nice to have: #574

**Comment by alimeshgi** [comment]
The list and other suggestions sound good to me. I don't have any further additions.

**Comment by savente93** [comment]
Given that we should release this week, and that there were a few hiccups along the way last time, I would like to start the release tomorrow, but at the least on Wednesday. So let's say that you have at least until the end of today to get your changes in if you want them to be included in the release, with possible extension until Wednesday upon request.

**Comment by hboisgon** [comment]
I worked a bit on installing examples via download, see PR #585 . Still have to update tests / docs but could one of you already review and decide if you want to include in this release or not and if you agree with this implementation?
If not, maybe for the review, do you think we can should include a zip version of the examples folder in the new release itself?

**Comment by hboisgon** [comment]
I was working on an example notebook for mesh and found some bugs... so I think still great if we could add the fixes from #594 to the release as this release contains the MeshModel improvements... I'm almost done with the notebook though so hope we can include this still!

**Comment by savente93** [comment]
I'll await that PR for now. We can postpone the release until tomorrow

**Comment by hboisgon** [comment]
The mesh model example and bugfixes are ready to review :)

**Comment by savente93** [comment]
Awaiting fixes of the docs deployment

**Comment by savente93** [comment]
Note to self: have verified that deployment happens successfully when a commit is made to the `gh-pages` branch. Therefore it seems that the upload action isn't making the commits correctly

**Comment by savente93** [comment]
fixed in #606
