### ISSUE TITLE
Should/could rioxarray be dropped as a dependency in 1.0?

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#571]
### Kind of request

Removing existing functionality

### Enhancement Description

Currently we still depend on an old version of rioxarray for a few functionalities, however most of the functionalities we need for the raster implementation are not covered by this, and are thus implemented inhouse in `raster.py`. I think it would be good to investigate if we can remove our dependency on this completely to make our environment a bit slimmer. This may or may not require a breaking change, so if we decide it is worth it I think this should be considered before we go to 1.0

### Additional Context

Opened this issue mainly for it to serve as a discussion point. Perhaps it won't have good ROI to do this, but reducing our footprint, and reducing the number of older dependencies we have is a good thing to strive for in my opinion.

**Comment by DirkEilander** [comment]
A quick comment. We use the latest rioxarray version which is still actively developed and the default xarray engine to read raster data, so nothing old here.

I do like to minimize the use of rioxarray  (opposite to previous strategy). 
- There is an issue to remove rio.crs #279. 
- Then, there are still the `rio.nodata` and `rio.write_notdata` and `rio.write_transform`. These could "easily" be replaced (requires separate issue)
- Finally, there is the `io.open_raster` function that uses rioxaray functionality to read raster files. This part I think will potentially be harder to replace and we should research what happens in rioxarray here.

**Comment by savente93** [comment]
In a discussion Dirk explained to me that rioxaray is used quite a lot for raster io things, so we can't drop this as a dependency so the issue is moot. Closing therefore
