### ISSUE TITLE
add skeleton plugin folder (based on wflow plugin) 

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#6]
- [ ] setup wflow model plugin, see https://github.com/Deltares/hydromt_wflow/issues/1
- [ ] move to core and generalize
- [ ] add readme with instructions

**Comment by hboisgon** [comment]
Added a plugin_boilerplate branch in hydromt_wflow to use as a template: https://github.com/Deltares/hydromt_wflow/tree/plugin_boilerplate 

Instead of a README, might be better to add a new page in the documentation linking to the template?
