### ISSUE TITLE
Consider bumping numpy version since numpy 1.21 is EOL

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/hydromt#614]
### Kind of request

Changing existing functionality

### Enhancement Description

I noticed `numpy>=1.20` in [pyproject.toml](https://github.com/Deltares/hydromt/blob/a7c510159ff6dd8863651f2fb14ce939b8560e59/pyproject.toml#L23). Since numpy 1.21 is EOL according to [this](https://endoflife.date/numpy) and [this](https://numpy.org/neps/nep-0029-deprecation_policy.html), it might be good to update this to `numpy>=1.22`. Optional of course, but might be someting to consider.

**Comment by savente93** [comment]
Thanks for reporting this! I've opened a pull request for it, so hopefully that will get merged soon enough. I've actually bumped it straight to 1.23 since the EOL of 1.22 is in two months.
