### ISSUE TITLE
move deltares_data.yml file

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#62]
Currently the deltares data is read from https://github.com/DirkEilander/hydromt-artifacts/releases/download/v0.0.4/data_sources_deltares.yml

As we are developing the deltares data and artifacts separately at different rates it is no longer necessary to keep these files together in the hydromt-artifacts repos and it might make more sense to move it back into this repos. 

We could simply keep it in a data folder in the repos which can be accessed by hydromt through the following link (link does not yet exist). In this url _main_ can also be replaced by a tag to refer to previous tagged versions.
https://raw.githubusercontent.com/Deltares/hydromt/main/data/data_sources_deltares.yml

The advantage of keeping it in the repos but outside the package folders is that it is not shipped with the releases and can be updated more frequently. This approach (data catalog yaml files in a data folder) could further be generalized to include other open data sources (e.g. BE data, DD opendap, STAC data) in the future.

**Comment by hboisgon** [comment]
In addition, it would be helpful to have a better link in the docs on where those data catalog files are stored, especially if they start to differ. For the deltares catalog this is quite nice to have as the file is never downloaded.

https://github.com/DirkEilander/hydromt-artifacts

**Comment by DirkEilander** [comment]
proposal: 

keep list of data_catalogs and versions in 
https://raw.githubusercontent.com/Deltares/hydromt/main/data/predefined_catalogs.yml
```
deltares_data:
   url: https://raw.githubusercontent.com/Deltares/hydromt/<version>/data/catalogs/deltares_data.yml
   version:
     latest: main
     v1: <git commit hash>
```
