### ISSUE TITLE
Transform/ boundary does not correspond with extent from data

### ISSUE THREAD

**Issue by dalmijn** [Deltares/hydromt#624]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Use: `GridModel` (no underscore) branch from hydromt_wflow

Run this script in debug mode.
n:\Deltabox\Postbox\Dalmijn, Brendan\PS\setup_wflow_test.py
(maybe drag it to a local place with the accompanying geojson).

Break here:
- `setup_laimaps` (wflow.py; hydromt_wflow): https://github.com/Deltares/hydromt_wflow/blob/af63b5a62d3d1ede84232fd9b9ab003477032948/hydromt_wflow/wflow.py#L919

This then goes through `get_rasterdataset` (data_catalog.py) and `get_data` (rasterdataset.py) and `_slice_data` (rasterdataset.py).

Break here:
- `_slice_spatial_dimensions` (rasterdataset.py): https://github.com/Deltares/hydromt/blob/f3be55fb3aaf44e1aceec0fe9acac82d6515768a/hydromt/data_adapter/rasterdataset.py#L547
- `clip_bbox` (raster.py): https://github.com/Deltares/hydromt/blob/f3be55fb3aaf44e1aceec0fe9acac82d6515768a/hydromt/raster.py#L1226

Then in `clip` the actual clipping happens but it need the indices from `clip_bbox`.  

### Current behaviour

While building a model with hydromt_wflow I noticed that the 'LAI' (leaf area index) was full of nodata values. 

When going through the steps (mentioned above) I noticed that clip_bbox in and on itself uses indices (derived from the transform) instead of coordinates (like it did in 0.8).

This example concerns itself with 'modis_lai' (rasterdataset from 'deltares_data'). 
This dataset had an extent in the x direction from -180 to 180. However the transform and the bounds reflect an extent from -180 to 167.99058.

This causes the indexing to be off by something like 2 degrees. 
Which coupled with the `reproject_like` to the overal dataset (with correct coordinates) causes nodata values.

(EDIT)
It happens here:
https://github.com/Deltares/hydromt/blob/f3be55fb3aaf44e1aceec0fe9acac82d6515768a/hydromt/gis_utils.py#L306-L322

'modis_lai' slightly excedes 180 degrees in the east. This prompts this method to kick into action, which then assumes that the data must be from 0-360 degrees (which its not). The eventual `sortby` (return statement) method then solidifies the wrong extent .

### Desired behaviour

I guess that the transform should be correct in regards to the coordinates shown by the data.

**Comment by DirkEilander** [comment]
I suggest to replace
`elif e > 180:  # 0E-360E > 180W - 180E`
by 
`elif w>= 0 and e > 180:  # 0E-360E > 180W - 180E`

**Comment by dalmijn** [comment]
I reopened this as we're looking to properly fix this.

**Comment by DirkEilander** [comment]
reproducible example

```
import hydromt
dc = hydromt.DataCatalog("deltares_data")
ds =dc.get_rasterdataset("modis_lai", bbox=[0, 0, 10, 10])
print(ds.raster.bounds)
```

This returns shifted bounds as the resolution is not properly computed.
