### ISSUE TITLE
Bug with get timeseries/forcing data timestamps

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#64]
Happens mostly with climate data.

In the data catalog we open these data using a {year} attribute in path and for some of them in combination with a time add (86400).
This results that when wanting to get forcing data for the 1st of January (eg from era5 or chirps), the resulting data starts at the 2nd instead.

**Comment by DirkEilander** [comment]
@hboisgon I was trying to resolve this in the `resolve_paths` method in data_adapter.py, specifically L731

https://github.com/Deltares/hydromt/blob/1f5cf5df836f817bb66b3abec49fb768544e4bd4/hydromt/data_adapter.py#L731

Can you provide a small reproducible code snippet so we can see what's  going on.

**Comment by hboisgon** [comment]
The dt solve is nice! The problem comes when using era5_daily data. In the different {year} file the first timestep starts at {year}-01-02 and the last timestep at {year+1}-01-01
