### ISSUE TITLE
management of (optional) dependencies

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#648]
### Kind of request

Changing existing functionality

### Enhancement Description

To keep the hydromt core lean I would like to keep the number of required dependencies to a minimum. Since the last release we have added pystac, pyogrio and pydantic. Can (some of) these be moved to optional dependencies? If HydroMT's core functionality (i.e., basically what is exposed via the cli) can work without and we can import the locally only that would have my preference.

My suggestion:
- `pystac` provides optional functionality and could be loaded inside the relevant functions only. I suggest to move it to the optional IO deps. 
- `pyogrio` is now used to get vector metadata with `pyogrio.read_info` which is used on most `DataCatalog.get_geodataframe` calls. It can optionally be used as engine to actually read the files if set in the driver_kwargs by the user. As it's hard to make it optional in the current implementation and geopandas will also make this the default moving forward I suggest to keep it. For now that means that both fiona and pyogrio will come with hydromt. 
- `pydantic` is required for the `hydromt check` cli command thus a required dependency.

@savente93, do you agree and if so, could you implement the first item?

**Comment by savente93** [comment]
I agree that pydantic is a required dependency, especially as we start using it more and more throughout the code base. As for the pyogio and pystac, I checked their sizes and they add a negligible amount, around 600K and 100K respectively. With some of the required dependencies clicking in at over 40M, I don't think it's worth worrying about this bit. I do agree that we could probably do some better trimming here at some point, but this at least is not going to make a noticeable difference, so I suggest we leave that for later.

**Comment by DirkEilander** [comment]
I'm fine to keep this for later. However, I think that size is not the only criteria we should keep in mind. With more decencies conflicts during installation are more likely, downstream bugs are more likely to affect our code, the installation process (dependency solving) may take longer etc. therefore, I think it's good to keep the list of required dependencies as lean as possible.
