### ISSUE TITLE
Improve the HydroMT installation guide

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/hydromt#675]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are unclear

### Location of the documentation

As an example, here is the location of installation guide for HydroMT-Wflow: https://deltares.github.io/hydromt_wflow/latest/getting_started/installation.html 

### Documentation problem

The current installation guide for HydroMT’s plugins (for example, HydroMT-wflow) is too technical and long for some users. 

### Suggested fix for documentation

As an option, we can explore Deltaforge to install the required python packages.

**Comment by savente93** [comment]
The installation guide is not much longer than the example. The reason it is longer is that we give more explanation/context and even with that, it is very short compared to other software. We could pair this down, but then we remove information that some users might want. Have we gotten complaints about this? If so, would they be available to expand further? I'd like more context on which parts are unclear this before we start cutting.

**Comment by alimeshgi** [comment]
pages should be changed to have seperate pages for installing with conda and with pip
