### ISSUE TITLE
Cant pass keyword when requesting known dataset

### ISSUE THREAD

**Issue by dalmijn** [Deltares/hydromt#678]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Use the 'deltares_data' data catalog.

Load this: `p:\1000365-002-wflow\tmp\usgs_wflow\models\TEST_MODEL\staticgeoms\region.geojson` as a geodataframe.

Request data for the first admin level `level1` of the `gadm` dataset (is a geopackage).

This looks like:
```python
import geopandas as gpd
from hydromt import DataCatalog

geom = gpd.read_file(r"p:\1000365-002-wflow\tmp\usgs_wflow\models\TEST_MODEL\staticgeoms\region.geojson")
d = DataCatalog(data_libs=["deltares_data"])

res = d.get_geodataframe("gadm", geom=geom, layer="level1")
```

This will not return the state, but instead the entire nation, i.e. `level0`.

### Current behaviour

When using a know dataset from the datacatalog, keyword arguments are not used at all.
I looked through the code and see this actually happening.
For `gadm` , `level0`, `level2` and `level3` are explicitly defined in the catalog yaml. I guess because of this.
However in this case I cannot request `level1` at all.

When I however request the data not by ID (i.e. `gadm`) but by path, it works.
As when the dataset set is unknown (which is the case when only a path is supplied) the keyword arguments do get used.

```python
p = d["gadm"].path

res = d.get_geodataframe(p, geom=geom, layer="level1")
```

This does work.

### Desired behaviour

Either be able to pass layer an option for requesting geodataframes or being able to just pass keyword arguments when requesting a known dataset from the data catalog.

**Comment by DirkEilander** [comment]
Just discussed with Brendan that for known datasets we should not use driver kwargs when requrestion data in setup methods because we don't know the driver used (e.g. for a rasterdataset this can use an xarray or rasterio function) and hence the available driver kwargs.

**Comment by savente93** [comment]
Does that mean this is a won't fix? If yes, please close the issue. If not, can we agree on the next steps for this issue?
