### ISSUE TITLE
Update artifact_data catalog for EPSG 54009

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#696]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

We have updated deltares_data catalog for data with crs 54009 but not artifact_data.

### Current behaviour

artifact_data with crs 54009 cannot be read

### Desired behaviour

Update artifact_data for data with crs: 54009 to crs: "ESRI:54009"

**Comment by savente93** [comment]
Fixed in v1 in #786
