### ISSUE TITLE
Add automated checking for the data catalog where possible

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#705]
### Kind of request

None

### Enhancement Description

The recent problem introduced with merging of the data catalog update prompted some discussion about what we can do to check the data calogue automatically. Given that actions does not have access to the P drive, and that doing actual checks on all the data would be prohibitively slow, it is not feasible to do semantic/functional checking for the data catalog, but we want to see what we can add to catch easy mistakes. currently the best check that is workable is to use the `hydromt check` functionality to make sure that the catalog is at least syntactically valid. If other ideas are brought up they can be added later. 

### Use case

Reduce the chances of errors causing issues for users when maintainers work on the catalog

**Comment by DirkEilander** [comment]
The hydromt check functionality is great! Could we also use that to test the supported hydromt versions with each catalog version in some way? 

In addition, it would be good to have a test (which we can only run locally for deltares_data) that read random small slices from all datasets as a check.
