### ISSUE TITLE
Documentation topics should be reorganised. 

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#716]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are unclear

### Documentation problem

Currently the documentation is very centered around the `build` `update` and other top level CLI actions. We're currently adding more functionallity that doesn't have a good home under this rubric yet, so this should be adressed. 

### Suggested fix for documentation

 - [x] beginner
 - [ ] advanced
 - [ ] plugin

**Comment by DirkEilander** [comment]
Currently we have the user guide and for plugins some info in the dev guide. 
We suggest to have three types of user guide for beginners, advanced users and plugin developers.

Incomplete skeleton:

For **beginners** we will cover: (plugin users)
- what is hydromt
- - model
- - plugins
- Model and DataCatalog structures
- Working with models
- - preparing your data 
- - workflow yaml files
- CLI

For **advanced** users
- architecture
- Model components
- Configuring and building a model
- - example with simple or hypothetical model
- Data Sources / Drivers / Adapters
- model processes

For **plugin** developers
- How to make your own Model
- How to register your plugin
- How to make your own Component
- How to make your own Driver
- How to make your own DataCatalog
- convention / best practices
- how to test your plugin
