### ISSUE TITLE
Improve cross platform support for the DataCatalog root

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#721]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Currently, for example the root of the deltares data catalog, is formatted as a windows path, which can cause issues when Hydromt is running in a linux environment. 

### Current behaviour

Mixing of paths can cause iether crashes or undefined behaviour. 

### Desired behaviour

hydromt can detect which platform it is running on and adjust the paths accordingly.

**Comment by DirkEilander** [comment]
suggested implementation:
List with roots ordered by priority. We loop over this list and check which root exists and build all paths from there.
