### ISSUE TITLE
User guide menu/content not shown in the latest version of the docs

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#744]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Open: https://deltares.github.io/hydromt/latest/user_guide/intro.html
Menu on the left is missing.

### Current behaviour

Missing menu:
![image](https://github.com/Deltares/hydromt/assets/45457510/9e5a4b01-cac5-4255-9345-b870ce912e9f)

### Desired behaviour

From stable version with menu to Models / Data etc.
![image](https://github.com/Deltares/hydromt/assets/45457510/4bffc28b-101d-40a9-9374-2ca8868897e4)

**Comment by JoostBuitink** [comment]
From what I understood, this is something that was broken in the PyData Sphinx Theme, but that should be fixed in v0.15.2 (https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.15.2, see third item). 

We had a similar issue with HydroMT-wflow, but rebuilding the docs (where we got the latest version of PyData Sphinx Theme) solved this issue, without needing to change anything on our end.

**Comment by hboisgon** [comment]
Thanks for your answer @JoostBuitink ! Good to know this is a known issue and might be fixed easily. @savente93 please try to regenerate latest docs to verify this before release hydromt to be sure. If all good then we can close this issue.

**Comment by JoostBuitink** [comment]
The docs still show to be build with PyData Sphinx Theme v0.15.1 (I think the cache is used instead of rebuilding the environment).

**Comment by savente93** [comment]
I refreshed the cache and that didn't seem to help so I'll have to investigate a bit deeper

**Comment by hboisgon** [comment]
Re-opened as this does not seem to be fixed (also the doc version switcher is missing quite some versions)

**Comment by savente93** [comment]
With some good tips from @dalmijn I think this is now fixed again. @hboisgon can you verify?
