### ISSUE TITLE
Bug in _parse_zoom_level of rasterdataset.py

### ISSUE THREAD

**Issue by roeldegoede** [Deltares/hydromt#754]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

For an arbitrary dataset with overviews, we would like to get the "overview" level close to the desired resolution, e.g.:

```
from hydromt import DataCatalog

data_catalog = DataCatalog()
da_fn = r"p:\11203312-012-profews\coastal_flooding\Ethekwini_Flooding\01_data\2020_flt_lidar\dem_1.tif"

# check resolution of original dataset (more or less 1m)
da = data_catalog.get_rasterdataset(da_fn)
da.raster.res

# resolution overview level 0 (is already 1 step coarser, so more or less 2m)
da = data_catalog.get_rasterdataset(da_fn, zoom_level = 0)
da.raster.res

# and here comes the error: 
da = data_catalog.get_rasterdataset(da_fn, zoom_level = (200, "meter")
```

### Current behaviour

At the moment, the overview level that is returned is 1 too high, because the original resolution of the data is parsed as overview_level=0, but according to rasterio, overview_level=0 is already a factor 2 coarses.

This results in errors when you ask for the coarsest level (see example). In this case, it is looking for an overview_level which is not present and therefore rasterio throws an error.

### Desired behaviour

Overviews that are aksed for should be 1 lower, hence overview 0 is 2 times coarser than the original resolution.

**Comment by DirkEilander** [comment]
I found the same bug just today and solved it for the example below. 
I've checked it also works for your data @roeldegoede. Perhaps you want to double check it (see linked PR).

```
#%%
from hydromt import DataCatalog 
import tempfile
import numpy as np

#%% read some raster data
dc = DataCatalog()
da = dc.get_rasterdataset('merit_hydro', variables=['elevtn'])
res = da.raster.res
#%% write to COG
cog_fn = tempfile.NamedTemporaryFile(suffix='.tif').name
da.raster.to_raster(cog_fn, driver="COG", overviews="auto")
#%% read COG with zoom_level =0 (native resolution)
da1 = dc.get_rasterdataset(cog_fn, zoom_level=(res[0], 'degree')) 
da1_res = da1.raster.res
assert np.allclose(da1.raster.res, res), f"{da1_res[0]} != {res[0]}"
```
