### ISSUE TITLE
Add filehandle to logger when setting `ModelRoot.path` in v1

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#779]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Setting the model root should create/update the logger file handle

### Current behaviour

We don't do anything with the logger in ModelRoot.path
https://github.com/Deltares/hydromt/blob/8556208b34a72f5a38db4a953864e0998070bf2f/hydromt/models/root.py#L33

### Desired behaviour

Closing the old logger file handle (if exits); copying the old logger file to the new path (new functionality); setting this as filehandler for the logger (see old code). 
When setting a new logger filehandle in overwrite mode, make sure any old hydromt.log file is deleted first (new functionality)
https://github.com/Deltares/hydromt/blob/3edef05bf25231f8ca9a888a5df37dec9ce10100/hydromt/models/model_api.py#L500

**Comment by savente93** [comment]
Fixed in #788
