### ISSUE TITLE
Data adapter era5_hourly

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#78]
Seems like the data adapter does not like to have twice the {variable} key in the path (eg for era5_hourly):
path: meteo/era5/{variable}/era5_{variable}_{year}_hourly.nc

This gives the ERROR: FileNotFoundError: No such file found: p:\wflow_global\hydromt\meteo\era5\{variable}\era5_{variable}_{year}_hourly.nc
(line 766 in resolve_paths in data_adapter.py)

Changing the path to : meteo/era5/*/era5_{variable}_{year}_hourly.nc makes it work.

@DirkEilander : I can either update the path in the hydromt-artifacts repository but I have the feeling it might be better to correct it in the data_adapter?

**Comment by DirkEilander** [comment]
I don't think the double `{variable}` is the issue. String formatting with twice the same variable name works fine:

```
>>> "\{variable}/{variable}".format(variable="precip")

'\\precip/precip'
```

From the error message it seems that the folder separator between `p:\wflow_global\hydromt\meteo\era5` and `{variable}` has disappeared. We will need to debug the code to find where this happens.
