### ISSUE TITLE
Release 0.9.4

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/hydromt#781]
### Kind of request

Adding new functionality

### Enhancement Description

The issue #776 reported slow read times for vector files, resulting in a drastic increase in model building time. This issue has since been addressed and fixed. With this new release, we aim to ensure that everyone benefits from this fix. 

### Additional Context

@hboisgon @DirkEilander @savente93 @Jaapel @Tjalling-dejong Please add any issues you would like included.

**Comment by DirkEilander** [comment]
it would be good to include #770

**Comment by hboisgon** [comment]
If it's not too long also #644 ? The PR is ready for review at #767 and then could appear in our stable docs version (docs on the CLI functions)

**Comment by savente93** [comment]
seems everything is in, so I'll cut a new release today
