### ISSUE TITLE
Deriving model regions from non-hydromt models

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#815]
### Kind of request

Adding new functionality

### Enhancement Description

Currently, if we cannot read the model region, we try to derive it from existing model files. We agreed that the components should be able to derive their own region so the users/plugins can overwrite this functionality if necessary. However we must still decide how to decide which components we should derive the region from if we cannot read. 
Ideally which component to derive the region from should be done by the model, but it is unclear yet how this should be specified. 

### Use case

This is to make it possible to hydromt to read modes that were not built by hydromt or where the region file was corrupted or missing.

**Comment by hboisgon** [comment]
This is now being discussed in #847

**Comment by deltamarnix** [comment]
We have decided the following:

Regions are actually never read. Regions are only written.
That means that a region is always derived from the original data it reads from.

We have implemented this by overriding the `_data_region()` property on all components that require this.
When writing the region, the region will be written to a geojson, but it will never be read again by HydroMT.
