### ISSUE TITLE
Setting path for `ModelRoot` with a TemporaryDirectory in windows tests results in error 

### ISSUE THREAD

**Issue by Tjalling-dejong** [Deltares/hydromt#820]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

```python
logger = logging.getLogger(__name__)

def test_model_root(tmp_dir):
    model_root = ModelRoot(path=tmp_dir)

```

### Current behaviour

..\..\..\miniforge\envs\hydromt-dev\Lib\tempfile.py:904: in __exit__
    self.cleanup()
..\..\..\miniforge\envs\hydromt-dev\Lib\tempfile.py:908: in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
..\..\..\miniforge\envs\hydromt-dev\Lib\tempfile.py:890: in _rmtree
    _shutil.rmtree(name, onerror=onerror)
..\..\..\miniforge\envs\hydromt-dev\Lib\shutil.py:759: in rmtree
    return _rmtree_unsafe(path, onerror)
..\..\..\miniforge\envs\hydromt-dev\Lib\shutil.py:622: in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
..\..\..\miniforge\envs\hydromt-dev\Lib\tempfile.py:881: in onerror
    cls._rmtree(path, ignore_errors=ignore_errors)
..\..\..\miniforge\envs\hydromt-dev\Lib\tempfile.py:890: in _rmtree
    _shutil.rmtree(name, onerror=onerror)
..\..\..\miniforge\envs\hydromt-dev\Lib\shutil.py:759: in rmtree
    return _rmtree_unsafe(path, onerror)
..\..\..\miniforge\envs\hydromt-dev\Lib\shutil.py:603: in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = 'C:\\Users\\jong\\AppData\\Local\\Temp\\tmp_vu8brc8\\hydromt.log'
onerror = <function TemporaryDirectory._rmtree.<locals>.onerror at 0x000002481E1F6AC0>

    def _rmtree_unsafe(path, onerror):
        try:
>           with os.scandir(path) as scandir_it:
E           NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\jong\\AppData\\Local\\Temp\\tmp_vu8brc8\\hydromt.log'

..\..\..\miniforge\envs\hydromt-dev\Lib\shutil.py:600: NotADirectoryError

### Desired behaviour

ModelRoot path can take a temporary directory for testing purposes

**Comment by savente93** [comment]
We briefly called about this and it turned out the problem was that the files were staying open after the test was done because the `tmp_dir` was used instead of `tmpdir` which uses `yield` instead of `return` . In any case it is solved now
