### ISSUE TITLE
Model CRS property

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#827]
### Kind of request

Adding new functionality

### Enhancement Description

The model CRS is currently derived from ``region``.
With the v1 re-organisation, it would be nice to have better support of user-defined model CRS.

I see two options:

1. In region.create or similar methods (grid.create, mesh.create etc) allow the user to pass the expected CRS of the model that can then be different from the region (eg bbox can only be 4326 at the moment)
2. Add a ``crs`` property of model at the ``__init__``. This property can then be re-used by all components.

### Additional Context

If we keep getting the model crs from region, then we have to re-think that a user can decide to write the region file in EPSG 4326 to follow WGS84 conventions. Because when reading crs will be 4326 rather than the original crs of region before writing.

**Comment by savente93** [comment]
I'm wondering if we might actually want to store the intended CRS in the model config? that way the region can be in whatever crs the data is and when reading the model will know to convert it. In similar situations other components can maintain their own CRS while doing the work, but know to convert it to the target CRS when writing. I don't have strong feelings about where this should live, but this seems like a sensible option to me. What do you think?

**Comment by hboisgon** [comment]
The model config is specific to each model (wflow, sfincs etc) and may not (so far for none of the models I think) store the crs. That is why I think as the __init__ of the model ie through the hydromt config could be an option (option2).
CRS of the model is important to know before writing: reprojection method from grid to grid depends on the variable so that is why we normally handle all reprojection from data to model data in the old setup, create and add_data mehods

**Comment by savente93** [comment]
That makes sense!

**Comment by savente93** [comment]
Fixed in #867
