### ISSUE TITLE
handling of single-point geometries by update_geometry() in vector.py

### ISSUE THREAD

**Issue by shartgring** [Deltares/hydromt#830]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

I am using a python script to create boundary conditions (for Delft3D-FM) using HydroMT. It consists of the code below. A NetCDF is read, a geometry is read, and both are combined into a Dataset with geospatial coordinates. The example below works correctly (as expected).

```
    results = xr.load_dataset(path_netcdf_wflow_results)

    Qup_coord = "Qbound_gauges_fm"
    Qup_data = results["Qbound"].rename({Qup_coord: "index"})
    Qup_data.name = 'Qupstream'

    Qup_gdf = gpd.read_file(path_geojson).copy().set_index("id")
    Qup_gdf.rename(columns={"id": "index"})

    Qup_data = Qup_data.vector.from_gdf(
                gdf=Qup_gdf, data=Qup_data, index_dim='index')

    # Qup_data = Qup_data.sel(index=1)
    Qup_fn = os.path.join(
            path_folder_output, f"{filename_output}_Q_upstream.nc")
    Qup_data.vector.to_netcdf(Qup_fn)
```
However, problems occur when creating a netcdf after indexing Qup_data (see commented line). When indexing a single point, the associated geometry changes from a GeoSeries or GeoDataFrame object into a pandas Series object (see also https://stackoverflow.com/questions/46046000/maintaining-the-geostructure-when-indexing-a-geodataframe). This in itself is not problematic, but an error is raised when using a vector.to_netcdf methods. As a result, the geometry type is not recognized as a GeoSeries and a ValueError is raised due to the following check in update_geometry: (https://github.com/Deltares/hydromt/blob/202874eb4fe3415d0608ea81cd61620af6f5816a/hydromt/vector.py#L308C1-L309C70):

```
        elif not isinstance(geometry, GeoSeries):
            raise ValueError("geometry should be a GeoSeries object")
```
I would say that this is a fault caused by how geopandas works. Still, it affects how HydroMT seems to handle single-point geometries, for example when creating a single-point upstream boundary condition in the form of a netcdf. Currently, I use xarrays .to_netcdf as a workaround instead of vector.to_netcdf

### Current behaviour

Raises a ValueError when dealing with single-point geometries

### Desired behaviour

Handling of single-point geometries by (for example?) converting the Series back to a GeoSeries or GeoDataFrame before raising the ValueError

**Comment by DirkEilander** [comment]
@shartgring Thanks for raising the issue. I have investigated it in #855, but it is not easy to fix. Similar to the pandas SO issue you reference I suggest to use `Qup_data.sel(index=[1])` (Note the `[..]` ). In that case the geometry array still has an index dimension and all code should work. Can you let me know if this solves the issue for you?

**Comment by hboisgon** [comment]
Hi @DirkEilander! I encountered the same issue and I tested with ``[]`` ie Qup_data.sel(index=[1]). And indeed this way the geometry of the GeoDataset is kept. For me this would be okay.

**Comment by shartgring** [comment]
Yes I tested it and it works fine, thanks! Indeed solves the issue
