### ISSUE TITLE
Create `raster` driver

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#857]
### Kind of request

Changing existing functionality

### Enhancement Description

Create a `raster` driver using the `rasterio` package.

Also: at https://github.com/Deltares/hydromt/blob/v0.9.4/hydromt/data_adapter/rasterdataset.py#L661 zoom levels are parsed based on the rasterio metadata.

In gis/raster.py there is a to_slippy_tiles function that results in a DataCatalog entry referring to the the previous raster driver, which should refer to a new driver #875 . This behaviour can be temporarily be deprecated.

### Use case

Open data using `rasterio`.

**Comment by DirkEilander** [comment]
For the raster driver the variable name should also be updated based on the variables argument in `DataCatalog.get_rasterdataset`, see #883. This is important to make sure we can still read tif files based on the path if not set in the data catalog without getting errors on the variable name.
