### ISSUE TITLE
Align for metadata_resolver

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#874]
### Kind of request

None

### Enhancement Description

In HydroMT RasterDatasetAdapter there is an align keyword used:
https://github.com/Deltares/hydromt/blob/main/hydromt/data_adapter/rasterdataset.py#L289
This is on aligning a bounding box based on a certain resolution, to be passed on to `ds.raster.clip_bbox`.
Does this bounding box also need to be aligned according when searching for relevant files based on an AoI using a bbox?

### Use case

Does this bounding box also need to be aligned according when searching for relevant files based on an AoI using a bbox?

**Comment by DirkEilander** [comment]
I've checked with SFINCS and Wflow plugins and this isn't used anywhere in which case I'm in favour of simplifying and removing this.
