### ISSUE TITLE
Create `XarrayDriver` for `GeodataSetSource`

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#877]
### Kind of request

Changing existing functionality

### Enhancement Description

The current `GeodataSetAdapter` has a `netcdf` and `zarr` drivers very similar to the `RasterDatasetAdapter`. This `XarrayDriver` should implement `RasterDatasetDriver`.

### Use case

Read netcdf and zarr files using the `GeodataSetSource`.

### Additional Context

Should also create the `GeodataSetSource` and `GeodataSetAdapter`, see #895

**Comment by savente93** [comment]
I was tempted to implement this one together with #895 but I actually think this would be a fairly easy one. Since @hboisgon still wanted to implement a driver I've decided to leave this one for her. You could take a look at this one once I'm done with #895, I'll let you know once that's the case.
