### ISSUE TITLE
Create `DataFrameSource`, `DataFrameAdapter` & `PandasDriver`

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#879]
### Kind of request

Changing existing functionality

### Enhancement Description

Because of the current simplicity of the drivers for a DataFrame, I would tackle these in one issue

```python
lf.driver in ["csv"]:
    df = pd.read_csv(path, **kwargs)
elif self.driver == "parquet":
    _ = kwargs.pop("index_col", None)
    df = pd.read_parquet(path, **kwargs)
elif self.driver in ["xls", "xlsx", "excel"]:
    df = pd.read_excel(path, engine="openpyxl", **kwargs)
elif self.driver in ["fwf"]:
    df = pd.read_fwf(path, **kwargs)
```

### Use case

Read in DataFrames

### Additional Context

Should also create `DataFrameSource` and `DataFrameAdapter`.

**Comment by DirkEilander** [comment]
We discussed to combine all pd.read_* functions into a single Driver to reduce the number of classes. The read function is selected based on the uri extension (and optional argument).
