### ISSUE TITLE
Implement `DataCatalog` export with new class model.

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#886]
### Kind of request

Changing existing functionality

### Enhancement Description

With the new classes, the `DataCatalog`s export functionality needs to be implemented.

### Use case

Export HydroMT data.

**Comment by hboisgon** [comment]
The command line interface to it is new but it's as old as the artifact data catalog :)
But indeed I think for alpha what is important is to see if the reshuffle works with plugins, not yet with the end/CLI users so if it's too long to implement then can be pushed to beta.

**Comment by Jaapel** [comment]
We did change the `DataCatalog`s depending classes, so everywhere we currently interact with a `DataAdapter` should change to `DataSource` and underlying classes.

**Comment by Jaapel** [comment]
Blocked by: https://github.com/Deltares/hydromt/issues/896

**Comment by savente93** [comment]
fixed in #1052
