### ISSUE TITLE
`DataSource.to_file` should fall back on a default driver

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#896]
### Kind of request

Changing existing functionality

### Enhancement Description

Currently, the `to_file` implementation writes with the same driver that it reads with. We need to fall back on a certain driver when this is not possible.

### Use case

When reading from an API, you do not want to write back. Instead, you'd like to save the data locally.

**Comment by savente93** [comment]
is this still necessary for alpha then?

**Comment by Jaapel** [comment]
Closed by #982
