### ISSUE TITLE
RoundTrip (de-)serialization for `DataSource`

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#900]
### Kind of request

Changing existing functionality

### Enhancement Description

When exporting data, `DataSource` should be serializable, so that is re-readable in the exported data catalog.
double data in metadata resolver (`unit_add`, `unit_mult`, `rename`) should not appear twice. Names should also appear back.

### Use case

Export of data

**Comment by Jaapel** [comment]
@savente93 @DirkEilander the `test_data_catalog_io_round_trip` already passes since I created the script to update data catalogs to v1. Anything else I am missing or can we close this?

**Comment by savente93** [comment]
The one exception I added there was that the roots won't be the same if you create from a dict, but other than that I think it's good so as far as I'm concerned you can close this, but it's up to you

**Comment by Jaapel** [comment]
Fixed in https://github.com/Deltares/hydromt/pull/970
