### ISSUE TITLE
`RasterDatasetAdapter` returns a `DataArray` in some cases in v0.x

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#913]
### Kind of request

Changing existing functionality

### Enhancement Description

The `RasterDatasetAdapter` returns a `xr.DataArray` in v0.x.
I assumed it would only return a Dataset based on the `ds` names everywhere and the tests, but apparently it does not. I found out when implementing: https://github.com/Deltares/hydromt/pull/883
Is this behaviour the we want to support or is it ok to return a xr.Dataset with just one `data_var`? Would make the code more clean.

### Use case

Reading in a single `.tif` file as a `RasterDataset`

**Comment by savente93** [comment]
We'll wait wait  Hélène has to say indeed, but I also have a preference for just returning datasets everywhere

**Comment by hboisgon** [comment]
I have a strong opinion yes and I would like to keep the current behavior to return a DataArray unless ``single_var_as_array`` flag is False.

The main reason is that if you return a dataset, then for dataray sources, the variable name becomes mandatory for sleection in the python code and we have to be even stricter in the data names and units requirements for hydromt data catalog to avoid clashes in variable names between plugins and it's already not easy as is... For example all the landuse data which are single raster would then need a common variable name in the data catalogs. So especially for most of the data with raster driver, we will now need a variable name.

Also the plugins when requesting a single variable when reading the dataset in their code then assume they get a datarray and then go on with their function. They would then need to add one extra line all the time to reduce the array themselves.

**Comment by savente93** [comment]
@Jaapel what would you like to see to close this issue?

**Comment by Jaapel** [comment]
We can agree to give xr.DataArray back at the highest level, and work with Datasets underneath?

**Comment by savente93** [comment]
Yes I think this is acceptable. do we need any code changes?

**Comment by Jaapel** [comment]
Not yet, let's close this and keep it mind for when we do the DataCatalog methods.
