### ISSUE TITLE
Make code compatible with newest version of xarray

### ISSUE THREAD

**Issue by Tjalling-dejong** [Deltares/hydromt#925]
### Kind of request

Changing existing functionality

### Enhancement Description

The xarray version is now pinned at v2024.3.0 because of breaking in changes in latest version of xarray (v2024.05.0). 
Using the latest version results in these errors:
![image](https://github.com/Deltares/hydromt/assets/93266159/09645a86-9d4b-4537-83b1-ad778e265e6c)

**Comment by savente93** [comment]
closed by #1013
