### ISSUE TITLE
`zoom_level` argument still needed?

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#984]
### Kind of request

None

### Enhancement Description

`RasterDatasetAdapter` still uses `zoom_level`: https://github.com/Deltares/hydromt/blob/v1/hydromt/data_adapter/rasterdataset.py#L150

### Use case

Keep the API clean and stable before v1 release.

**Comment by DirkEilander** [comment]
zoom_level is needed as an argument of the `DataCatalog.get_rasterdataset` method and should be passed to the Driver. I'm not sure it is required in the `RasterDatasetAdapter`

**Comment by Jaapel** [comment]
Fixed in https://github.com/Deltares/hydromt/pull/1024
